// This file was generated by Safe DDS code generator, which is
// Copyright (C) 2023, Proyectos y Sistemas de Mantenimiento SL (eProsima)
//
// This program is commercial software licensed under the terms of the
// eProsima Software License Agreement Rev 03 (the "License")
//
// You may obtain a copy of the License at
// https://www.eprosima.com/licenses/LICENSE-REV03

/*!
 * @file common.hpp
 * This header file contains the declaration of the types described in the IDL file.
 *
 * This file was generated by Safe-DDS-gen.
 */

#ifndef SAFEDDS_GENERATED__SAFE_EDGE_COMMON_COMMON_HPP
#define SAFEDDS_GENERATED__SAFE_EDGE_COMMON_COMMON_HPP

#include <safedds/dds/DomainParticipant.hpp>
#include <safedds/dds/TypedTypeSupport.hpp>
#include <safedds/memory/IStringView.hpp>
#include <safedds/memory/Alignment.hpp>
#include <safedds/memory/Optional.hpp>
#include <safedds/memory/byte_array/ByteArrayView.hpp>
#include <safedds/protocol/rtps/RTPSTypeSupport.hpp>
#include <safedds/portable/Endianness.hpp>
#include <safedds/portable/MD5.hpp>
#include <safedds/portable/String.hpp>
#include <safedds/serialization/cdr/Alignment.hpp>
#include <safedds/serialization/cdr/Deserializer.hpp>
#include <safedds/serialization/cdr/Serializer.hpp>
#include <safedds/serialization/cdr/XCDRVersion.hpp>
#include <safedds/serialization/RepresentationHeader.hpp>
#include <safedds/portable/SafeCasts.hpp>

#include <SafeDDSGenAux.hpp>
#include <SafeDDSGenUtils.hpp>

#include <array>
#include <vector>
#include <string>
#include <map>



namespace safe_edge {
    namespace common {

        // Forward declaration
        struct HeaderSerialization;

        /*!
         * @brief This struct represents the structure Header defined by the user in the IDL file.
         * @ingroup common
         */
        struct Header
        {
            using SerializationStruct = HeaderSerialization;

            static constexpr eprosima::safedds::gen::IDLExtensibilityKind IDL_EXTENSIBILITY = eprosima::safedds::gen::IDLExtensibilityKind::APPENDABLE;

            /// Member source
            std::string source ;
            /// Member timestamp_ms
            uint64_t timestamp_ms = 0;
            /// Member trace_id
            std::string trace_id ;

            // Ensure bounds
            static_assert(255 != 0, "source shall be bounded or --default_unbounded_max_size shall be used");

            static_assert(255 != 0, "trace_id shall be bounded or --default_unbounded_max_size shall be used");
        };

        struct HeaderSerialization
        {
            static constexpr uint32_t max_serialized_size()
            {
                // Return the precalculated max_serialized_size plus required:
                // - Representation Header size (+4 B) since it is serialized in the typesupport serialization method
                // - Alignment to 4 B since the  serialization method adds padding
                return eprosima::safedds::memory::align_to<532ULL + 4ULL, 4U>();
            }

            static constexpr uint32_t max_key_serialized_size()
            {
                return 0ULL;
            }

            static eprosima::safedds::ReturnCode serialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const Header& sample)
            {
                using namespace safe_edge::common;

                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(
                    ser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                    eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                    eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR);

                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.source.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;
                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.trace_id.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(0, sample.source) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(1, sample.timestamp_ms) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(2, sample.trace_id) : ret;

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;
            }

            static eprosima::safedds::ReturnCode deserialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& deser,
                    Header& sample)
            {
                using namespace safe_edge::common;

                // Store the values of the external members in auxiliary variables

                sample = {};

                // Restore the values of the external members

                const eprosima::safedds::gen::EncodingAlgorithm encoding =
                    deser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                        eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                        eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR;

                return deser.deserialize_type(encoding,
                [&sample](eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& inner_deser, const uint32_t id) -> eprosima::safedds::ReturnCode
                {
                    eprosima::safedds::ReturnCode ret_value = eprosima::safedds::ReturnCode::OK;
                    switch (id)
                    {
                            case 0:
                                ret_value = inner_deser.deserialize_member(sample.source);
                                break;

                            case 1:
                                ret_value = inner_deser.deserialize_member(sample.timestamp_ms);
                                break;

                            case 2:
                                ret_value = inner_deser.deserialize_member(sample.trace_id);
                                break;

                    default:
                        ret_value = eprosima::safedds::ReturnCode::UNIMPLEMENTED;
                        break;
                    }
                    return ret_value;
                });
            }

            static eprosima::safedds::ReturnCode serialize_key(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const Header& sample)
            {
                using namespace safe_edge::common;


                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR2);

                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.source.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;
                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.trace_id.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(0, sample.source) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(1, sample.timestamp_ms) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(2, sample.trace_id) : ret;


                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;

            }

            static bool compare(
                    const Header& first,
                    const Header& second)
            {
                using namespace safe_edge::common;

                bool ret = true;

                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.source, second.source);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.timestamp_ms, second.timestamp_ms);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.trace_id, second.trace_id);

                return ret;
            }
        };


        struct HeaderTypeSupport :
            public eprosima::safedds::dds::TypedTypeSupport<Header>
        {
            using DataType = Header;

            eprosima::safedds::dds::ReturnCode register_type(
                    eprosima::safedds::dds::DomainParticipant& participant,
                    const eprosima::safedds::memory::IStringView& type_name) noexcept override
            {
                return participant.register_type(*this, type_name);
            }

            const eprosima::safedds::memory::IStringView& get_type_name() const noexcept override
            {
                static constexpr char const* default_name = "safe_edge::common::Header";
                static const eprosima::safedds::memory::container::StaticString256 typesupport_name(default_name);
                return typesupport_name;
            }

            uint32_t max_serialized_size() const noexcept override
            {
                return HeaderSerialization::max_serialized_size();
            }

            uint32_t serialized_size(
                    const Header& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == sample_serialized_size(sample, xcdr_version, sample_size))
                {
                    sample_size = eprosima::safedds::memory::align_to(
                        eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() +
                        sample_size, 4);
                }

                return sample_size;
            }

            eprosima::safedds::ReturnCode serialize(
                    const Header& sample,
                    eprosima::safedds::memory::IByteArrayView& buffer,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                eprosima::safedds::ReturnCode ret =
                    (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version) || (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2 == xcdr_version) ?
                    eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    if(eprosima::safedds::portable::MACHINE_ENDIANNESS == eprosima::safedds::platform::Endianness::SAFEDDS_BIG_ENDIAN)
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_BE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_BE;
                    }
                    else
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_LE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_LE;
                    }
                }

                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = sample_serialized_size(sample, xcdr_version, sample_size);
                }

                uint32_t aligned_size = eprosima::safedds::memory::align_to(sample_size, 4);
                uint32_t payload_size = eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() + aligned_size;

                if (eprosima::safedds::ReturnCode::OK == ret && buffer.size() >= payload_size)
                {
                    // Indicate the number of padding bytes in the encapsulation options
                    uint32_t required_padding = aligned_size - sample_size;
                    representation_header.encapsulation_options[1] = static_cast<uint8_t>(required_padding);

                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                    ret = ser_rh.serialize_array(
                        representation_header.encapsulation_kind.data(),
                        eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_KIND_SIZE);

                    if (eprosima::safedds::ReturnCode::OK == ret)
                    {
                        ret = ser_rh.serialize_array(
                            representation_header.encapsulation_options.data(), eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_OPTIONS_SIZE);
                    }

                    if (eprosima::safedds::ReturnCode::OK == ret && sample_size > 0)
                    {
                        eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {
                            &buffer[ser_rh.serializer_used_size()],
                            ser_rh.serializer_remaining_size()
                        };

                        eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(payload_view, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);

                        ret = HeaderSerialization::serialize(ser, sample);

                        // Add padding
                        for (uint32_t i = 0; (eprosima::safedds::ReturnCode::OK == ret) && (i < required_padding); ++i)
                        {
                            ret = ser.serialize('\0');
                        }
                    }
                }

                return ret;
            }

            eprosima::safedds::ReturnCode deserialize(
                    const eprosima::safedds::memory::IConstByteArrayView& buffer,
                    Header& sample) const noexcept override
            {
                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                eprosima::safedds::serialization::cdr::Deserializer deserializer_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1);
                eprosima::safedds::ReturnCode ret = eprosima::safedds::protocol::rtps::RTPSTypeSupport::deserialize(deserializer_rh, representation_header);

                // Check expected RepresentationHeader type to be valid and supported
                const bool is_cdr_v1 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] <= 0x03U);
                const bool is_cdr_v2 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] >= 0x06U && representation_header.encapsulation_kind[1U] <= 0x0BU);
                ret = (eprosima::safedds::ReturnCode::OK == ret && (is_cdr_v1 || is_cdr_v2)) ? eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                // Skip payload
                eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {nullptr, 0U};
                uint32_t remaining_size = deserializer_rh.deserializer_remaining_size();
                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    uint32_t padding_size = static_cast<uint32_t>(representation_header.encapsulation_options[1] & 0x03);
                    if (remaining_size >= padding_size)
                    {
                        remaining_size -= padding_size;
                        ret = deserializer_rh.deserializer_skip(remaining_size, payload_view);
                    }
                    else
                    {
                        ret = eprosima::safedds::ReturnCode::SERIALIZATION_INVALID_REPRESENTATION;
                    }
                }

                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    // Get received endianness and deserialize payload
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer deserializer(payload_view,
                        representation_header.get_endianness(),
                        is_cdr_v1 ? eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 : eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2);

                    ret = HeaderSerialization::deserialize(deserializer, sample);
                }

                return ret;
            }

            eprosima::safedds::dds::ReturnCode get_key(
                    const Header& data,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(data);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            eprosima::safedds::dds::ReturnCode get_key_from_payload(
                    const eprosima::safedds::memory::IConstByteArrayView& view,
                    const eprosima::safedds::protocol::PayloadKind& kind,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(view);
                static_cast<void>(kind);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            bool has_keys() const noexcept override
            {
                return false;
            }

        private:

            eprosima::safedds::ReturnCode sample_serialized_size(
                    const Header& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version,
                    uint32_t & serialized_size) const noexcept
            {
                serialized_size = 0;

                // Create a fake serializer to calculate the serialized size
                eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                eprosima::safedds::ReturnCode ret = HeaderSerialization::serialize(ser, sample);

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    serialized_size = ser.serializer_used_size();
                }

                return ret;
            }

        };



        // Forward declaration
        struct GeoPointSerialization;

        /*!
         * @brief This struct represents the structure GeoPoint defined by the user in the IDL file.
         * @ingroup common
         */
        struct GeoPoint
        {
            using SerializationStruct = GeoPointSerialization;

            static constexpr eprosima::safedds::gen::IDLExtensibilityKind IDL_EXTENSIBILITY = eprosima::safedds::gen::IDLExtensibilityKind::APPENDABLE;

            /// Member latitude
            double latitude = 0.0;
            /// Member longitude
            double longitude = 0.0;

            // Ensure bounds
        };

        struct GeoPointSerialization
        {
            static constexpr uint32_t max_serialized_size()
            {
                // Return the precalculated max_serialized_size plus required:
                // - Representation Header size (+4 B) since it is serialized in the typesupport serialization method
                // - Alignment to 4 B since the  serialization method adds padding
                return eprosima::safedds::memory::align_to<24ULL + 4ULL, 4U>();
            }

            static constexpr uint32_t max_key_serialized_size()
            {
                return 0ULL;
            }

            static eprosima::safedds::ReturnCode serialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const GeoPoint& sample)
            {
                using namespace safe_edge::common;

                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(
                    ser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                    eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                    eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR);



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(0, sample.latitude) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(1, sample.longitude) : ret;

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;
            }

            static eprosima::safedds::ReturnCode deserialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& deser,
                    GeoPoint& sample)
            {
                using namespace safe_edge::common;

                // Store the values of the external members in auxiliary variables

                sample = {};

                // Restore the values of the external members

                const eprosima::safedds::gen::EncodingAlgorithm encoding =
                    deser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                        eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                        eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR;

                return deser.deserialize_type(encoding,
                [&sample](eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& inner_deser, const uint32_t id) -> eprosima::safedds::ReturnCode
                {
                    eprosima::safedds::ReturnCode ret_value = eprosima::safedds::ReturnCode::OK;
                    switch (id)
                    {
                            case 0:
                                ret_value = inner_deser.deserialize_member(sample.latitude);
                                break;

                            case 1:
                                ret_value = inner_deser.deserialize_member(sample.longitude);
                                break;

                    default:
                        ret_value = eprosima::safedds::ReturnCode::UNIMPLEMENTED;
                        break;
                    }
                    return ret_value;
                });
            }

            static eprosima::safedds::ReturnCode serialize_key(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const GeoPoint& sample)
            {
                using namespace safe_edge::common;


                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR2);



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(0, sample.latitude) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(1, sample.longitude) : ret;


                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;

            }

            static bool compare(
                    const GeoPoint& first,
                    const GeoPoint& second)
            {
                using namespace safe_edge::common;

                bool ret = true;

                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.latitude, second.latitude);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.longitude, second.longitude);

                return ret;
            }
        };


        struct GeoPointTypeSupport :
            public eprosima::safedds::dds::TypedTypeSupport<GeoPoint>
        {
            using DataType = GeoPoint;

            eprosima::safedds::dds::ReturnCode register_type(
                    eprosima::safedds::dds::DomainParticipant& participant,
                    const eprosima::safedds::memory::IStringView& type_name) noexcept override
            {
                return participant.register_type(*this, type_name);
            }

            const eprosima::safedds::memory::IStringView& get_type_name() const noexcept override
            {
                static constexpr char const* default_name = "safe_edge::common::GeoPoint";
                static const eprosima::safedds::memory::container::StaticString256 typesupport_name(default_name);
                return typesupport_name;
            }

            uint32_t max_serialized_size() const noexcept override
            {
                return GeoPointSerialization::max_serialized_size();
            }

            uint32_t serialized_size(
                    const GeoPoint& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == sample_serialized_size(sample, xcdr_version, sample_size))
                {
                    sample_size = eprosima::safedds::memory::align_to(
                        eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() +
                        sample_size, 4);
                }

                return sample_size;
            }

            eprosima::safedds::ReturnCode serialize(
                    const GeoPoint& sample,
                    eprosima::safedds::memory::IByteArrayView& buffer,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                eprosima::safedds::ReturnCode ret =
                    (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version) || (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2 == xcdr_version) ?
                    eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    if(eprosima::safedds::portable::MACHINE_ENDIANNESS == eprosima::safedds::platform::Endianness::SAFEDDS_BIG_ENDIAN)
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_BE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_BE;
                    }
                    else
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_LE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_LE;
                    }
                }

                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = sample_serialized_size(sample, xcdr_version, sample_size);
                }

                uint32_t aligned_size = eprosima::safedds::memory::align_to(sample_size, 4);
                uint32_t payload_size = eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() + aligned_size;

                if (eprosima::safedds::ReturnCode::OK == ret && buffer.size() >= payload_size)
                {
                    // Indicate the number of padding bytes in the encapsulation options
                    uint32_t required_padding = aligned_size - sample_size;
                    representation_header.encapsulation_options[1] = static_cast<uint8_t>(required_padding);

                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                    ret = ser_rh.serialize_array(
                        representation_header.encapsulation_kind.data(),
                        eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_KIND_SIZE);

                    if (eprosima::safedds::ReturnCode::OK == ret)
                    {
                        ret = ser_rh.serialize_array(
                            representation_header.encapsulation_options.data(), eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_OPTIONS_SIZE);
                    }

                    if (eprosima::safedds::ReturnCode::OK == ret && sample_size > 0)
                    {
                        eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {
                            &buffer[ser_rh.serializer_used_size()],
                            ser_rh.serializer_remaining_size()
                        };

                        eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(payload_view, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);

                        ret = GeoPointSerialization::serialize(ser, sample);

                        // Add padding
                        for (uint32_t i = 0; (eprosima::safedds::ReturnCode::OK == ret) && (i < required_padding); ++i)
                        {
                            ret = ser.serialize('\0');
                        }
                    }
                }

                return ret;
            }

            eprosima::safedds::ReturnCode deserialize(
                    const eprosima::safedds::memory::IConstByteArrayView& buffer,
                    GeoPoint& sample) const noexcept override
            {
                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                eprosima::safedds::serialization::cdr::Deserializer deserializer_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1);
                eprosima::safedds::ReturnCode ret = eprosima::safedds::protocol::rtps::RTPSTypeSupport::deserialize(deserializer_rh, representation_header);

                // Check expected RepresentationHeader type to be valid and supported
                const bool is_cdr_v1 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] <= 0x03U);
                const bool is_cdr_v2 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] >= 0x06U && representation_header.encapsulation_kind[1U] <= 0x0BU);
                ret = (eprosima::safedds::ReturnCode::OK == ret && (is_cdr_v1 || is_cdr_v2)) ? eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                // Skip payload
                eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {nullptr, 0U};
                uint32_t remaining_size = deserializer_rh.deserializer_remaining_size();
                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    uint32_t padding_size = static_cast<uint32_t>(representation_header.encapsulation_options[1] & 0x03);
                    if (remaining_size >= padding_size)
                    {
                        remaining_size -= padding_size;
                        ret = deserializer_rh.deserializer_skip(remaining_size, payload_view);
                    }
                    else
                    {
                        ret = eprosima::safedds::ReturnCode::SERIALIZATION_INVALID_REPRESENTATION;
                    }
                }

                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    // Get received endianness and deserialize payload
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer deserializer(payload_view,
                        representation_header.get_endianness(),
                        is_cdr_v1 ? eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 : eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2);

                    ret = GeoPointSerialization::deserialize(deserializer, sample);
                }

                return ret;
            }

            eprosima::safedds::dds::ReturnCode get_key(
                    const GeoPoint& data,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(data);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            eprosima::safedds::dds::ReturnCode get_key_from_payload(
                    const eprosima::safedds::memory::IConstByteArrayView& view,
                    const eprosima::safedds::protocol::PayloadKind& kind,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(view);
                static_cast<void>(kind);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            bool has_keys() const noexcept override
            {
                return false;
            }

        private:

            eprosima::safedds::ReturnCode sample_serialized_size(
                    const GeoPoint& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version,
                    uint32_t & serialized_size) const noexcept
            {
                serialized_size = 0;

                // Create a fake serializer to calculate the serialized size
                eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                eprosima::safedds::ReturnCode ret = GeoPointSerialization::serialize(ser, sample);

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    serialized_size = ser.serializer_used_size();
                }

                return ret;
            }

        };


        enum class HealthStatus : int32_t
        {
            HEALTH_UNKNOWN ,
            HEALTH_OK ,
            HEALTH_DEGRADED ,
            HEALTH_ERROR 
        };


        // Forward declaration
        struct ServiceHeartbeatSerialization;

        /*!
         * @brief This struct represents the structure ServiceHeartbeat defined by the user in the IDL file.
         * @ingroup common
         */
        struct ServiceHeartbeat
        {
            using SerializationStruct = ServiceHeartbeatSerialization;

            static constexpr eprosima::safedds::gen::IDLExtensibilityKind IDL_EXTENSIBILITY = eprosima::safedds::gen::IDLExtensibilityKind::APPENDABLE;

            /// Member header_st
            safe_edge::common::Header header_st ;
            /// Member service_name
            std::string service_name ;
            /// Member status
            safe_edge::common::HealthStatus status = safe_edge::common::HealthStatus::HEALTH_UNKNOWN;
            /// Member detail
            std::string detail ;

            // Ensure bounds
            static_assert(255 != 0, "service_name shall be bounded or --default_unbounded_max_size shall be used");

            static_assert(255 != 0, "detail shall be bounded or --default_unbounded_max_size shall be used");
        };

        struct ServiceHeartbeatSerialization
        {
            static constexpr uint32_t max_serialized_size()
            {
                // Return the precalculated max_serialized_size plus required:
                // - Representation Header size (+4 B) since it is serialized in the typesupport serialization method
                // - Alignment to 4 B since the  serialization method adds padding
                return eprosima::safedds::memory::align_to<1064ULL + 4ULL, 4U>();
            }

            static constexpr uint32_t max_key_serialized_size()
            {
                return 0ULL;
            }

            static eprosima::safedds::ReturnCode serialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const ServiceHeartbeat& sample)
            {
                using namespace safe_edge::common;

                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(
                    ser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                    eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                    eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR);

                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.service_name.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;
                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.detail.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(0, sample.header_st) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(1, sample.service_name) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(2, sample.status) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(3, sample.detail) : ret;

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;
            }

            static eprosima::safedds::ReturnCode deserialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& deser,
                    ServiceHeartbeat& sample)
            {
                using namespace safe_edge::common;

                // Store the values of the external members in auxiliary variables

                sample = {};

                // Restore the values of the external members

                const eprosima::safedds::gen::EncodingAlgorithm encoding =
                    deser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                        eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                        eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR;

                return deser.deserialize_type(encoding,
                [&sample](eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& inner_deser, const uint32_t id) -> eprosima::safedds::ReturnCode
                {
                    eprosima::safedds::ReturnCode ret_value = eprosima::safedds::ReturnCode::OK;
                    switch (id)
                    {
                            case 0:
                                ret_value = inner_deser.deserialize_member(sample.header_st);
                                break;

                            case 1:
                                ret_value = inner_deser.deserialize_member(sample.service_name);
                                break;

                            case 2:
                                ret_value = inner_deser.deserialize_member(sample.status);
                                break;

                            case 3:
                                ret_value = inner_deser.deserialize_member(sample.detail);
                                break;

                    default:
                        ret_value = eprosima::safedds::ReturnCode::UNIMPLEMENTED;
                        break;
                    }
                    return ret_value;
                });
            }

            static eprosima::safedds::ReturnCode serialize_key(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const ServiceHeartbeat& sample)
            {
                using namespace safe_edge::common;


                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR2);

                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.service_name.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;
                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.detail.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(0, sample.header_st) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(1, sample.service_name) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(2, sample.status) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(3, sample.detail) : ret;


                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;

            }

            static bool compare(
                    const ServiceHeartbeat& first,
                    const ServiceHeartbeat& second)
            {
                using namespace safe_edge::common;

                bool ret = true;

                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.header_st, second.header_st);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.service_name, second.service_name);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.status, second.status);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.detail, second.detail);

                return ret;
            }
        };


        struct ServiceHeartbeatTypeSupport :
            public eprosima::safedds::dds::TypedTypeSupport<ServiceHeartbeat>
        {
            using DataType = ServiceHeartbeat;

            eprosima::safedds::dds::ReturnCode register_type(
                    eprosima::safedds::dds::DomainParticipant& participant,
                    const eprosima::safedds::memory::IStringView& type_name) noexcept override
            {
                return participant.register_type(*this, type_name);
            }

            const eprosima::safedds::memory::IStringView& get_type_name() const noexcept override
            {
                static constexpr char const* default_name = "safe_edge::common::ServiceHeartbeat";
                static const eprosima::safedds::memory::container::StaticString256 typesupport_name(default_name);
                return typesupport_name;
            }

            uint32_t max_serialized_size() const noexcept override
            {
                return ServiceHeartbeatSerialization::max_serialized_size();
            }

            uint32_t serialized_size(
                    const ServiceHeartbeat& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == sample_serialized_size(sample, xcdr_version, sample_size))
                {
                    sample_size = eprosima::safedds::memory::align_to(
                        eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() +
                        sample_size, 4);
                }

                return sample_size;
            }

            eprosima::safedds::ReturnCode serialize(
                    const ServiceHeartbeat& sample,
                    eprosima::safedds::memory::IByteArrayView& buffer,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                eprosima::safedds::ReturnCode ret =
                    (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version) || (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2 == xcdr_version) ?
                    eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    if(eprosima::safedds::portable::MACHINE_ENDIANNESS == eprosima::safedds::platform::Endianness::SAFEDDS_BIG_ENDIAN)
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_BE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_BE;
                    }
                    else
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_LE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_LE;
                    }
                }

                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = sample_serialized_size(sample, xcdr_version, sample_size);
                }

                uint32_t aligned_size = eprosima::safedds::memory::align_to(sample_size, 4);
                uint32_t payload_size = eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() + aligned_size;

                if (eprosima::safedds::ReturnCode::OK == ret && buffer.size() >= payload_size)
                {
                    // Indicate the number of padding bytes in the encapsulation options
                    uint32_t required_padding = aligned_size - sample_size;
                    representation_header.encapsulation_options[1] = static_cast<uint8_t>(required_padding);

                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                    ret = ser_rh.serialize_array(
                        representation_header.encapsulation_kind.data(),
                        eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_KIND_SIZE);

                    if (eprosima::safedds::ReturnCode::OK == ret)
                    {
                        ret = ser_rh.serialize_array(
                            representation_header.encapsulation_options.data(), eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_OPTIONS_SIZE);
                    }

                    if (eprosima::safedds::ReturnCode::OK == ret && sample_size > 0)
                    {
                        eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {
                            &buffer[ser_rh.serializer_used_size()],
                            ser_rh.serializer_remaining_size()
                        };

                        eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(payload_view, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);

                        ret = ServiceHeartbeatSerialization::serialize(ser, sample);

                        // Add padding
                        for (uint32_t i = 0; (eprosima::safedds::ReturnCode::OK == ret) && (i < required_padding); ++i)
                        {
                            ret = ser.serialize('\0');
                        }
                    }
                }

                return ret;
            }

            eprosima::safedds::ReturnCode deserialize(
                    const eprosima::safedds::memory::IConstByteArrayView& buffer,
                    ServiceHeartbeat& sample) const noexcept override
            {
                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                eprosima::safedds::serialization::cdr::Deserializer deserializer_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1);
                eprosima::safedds::ReturnCode ret = eprosima::safedds::protocol::rtps::RTPSTypeSupport::deserialize(deserializer_rh, representation_header);

                // Check expected RepresentationHeader type to be valid and supported
                const bool is_cdr_v1 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] <= 0x03U);
                const bool is_cdr_v2 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] >= 0x06U && representation_header.encapsulation_kind[1U] <= 0x0BU);
                ret = (eprosima::safedds::ReturnCode::OK == ret && (is_cdr_v1 || is_cdr_v2)) ? eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                // Skip payload
                eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {nullptr, 0U};
                uint32_t remaining_size = deserializer_rh.deserializer_remaining_size();
                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    uint32_t padding_size = static_cast<uint32_t>(representation_header.encapsulation_options[1] & 0x03);
                    if (remaining_size >= padding_size)
                    {
                        remaining_size -= padding_size;
                        ret = deserializer_rh.deserializer_skip(remaining_size, payload_view);
                    }
                    else
                    {
                        ret = eprosima::safedds::ReturnCode::SERIALIZATION_INVALID_REPRESENTATION;
                    }
                }

                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    // Get received endianness and deserialize payload
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer deserializer(payload_view,
                        representation_header.get_endianness(),
                        is_cdr_v1 ? eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 : eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2);

                    ret = ServiceHeartbeatSerialization::deserialize(deserializer, sample);
                }

                return ret;
            }

            eprosima::safedds::dds::ReturnCode get_key(
                    const ServiceHeartbeat& data,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(data);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            eprosima::safedds::dds::ReturnCode get_key_from_payload(
                    const eprosima::safedds::memory::IConstByteArrayView& view,
                    const eprosima::safedds::protocol::PayloadKind& kind,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(view);
                static_cast<void>(kind);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            bool has_keys() const noexcept override
            {
                return false;
            }

        private:

            eprosima::safedds::ReturnCode sample_serialized_size(
                    const ServiceHeartbeat& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version,
                    uint32_t & serialized_size) const noexcept
            {
                serialized_size = 0;

                // Create a fake serializer to calculate the serialized size
                eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                eprosima::safedds::ReturnCode ret = ServiceHeartbeatSerialization::serialize(ser, sample);

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    serialized_size = ser.serializer_used_size();
                }

                return ret;
            }

        };


        enum class PolicyMode : int32_t
        {
            POLICY_UNKNOWN ,
            POLICY_NOMINAL ,
            POLICY_LOW_SOC ,
            POLICY_EDGE_AUTONOMOUS ,
            POLICY_DEGRADED_SERVER_DOWN ,
            POLICY_DEGRADED_COMPLETE 
        };

    } // namespace common
} // namespace safe_edge

#endif  // SAFEDDS_GENERATED__SAFE_EDGE_COMMON_COMMON_HPP