// This file was generated by Safe DDS code generator, which is
// Copyright (C) 2023, Proyectos y Sistemas de Mantenimiento SL (eProsima)
//
// This program is commercial software licensed under the terms of the
// eProsima Software License Agreement Rev 03 (the "License")
//
// You may obtain a copy of the License at
// https://www.eprosima.com/licenses/LICENSE-REV03

/*!
 * @file edge.hpp
 * This header file contains the declaration of the types described in the IDL file.
 *
 * This file was generated by Safe-DDS-gen.
 */

#ifndef SAFEDDS_GENERATED__SAFE_EDGE_EDGE_EDGE_HPP
#define SAFEDDS_GENERATED__SAFE_EDGE_EDGE_EDGE_HPP

#include <safedds/dds/DomainParticipant.hpp>
#include <safedds/dds/TypedTypeSupport.hpp>
#include <safedds/memory/IStringView.hpp>
#include <safedds/memory/Alignment.hpp>
#include <safedds/memory/Optional.hpp>
#include <safedds/memory/byte_array/ByteArrayView.hpp>
#include <safedds/protocol/rtps/RTPSTypeSupport.hpp>
#include <safedds/portable/Endianness.hpp>
#include <safedds/portable/MD5.hpp>
#include <safedds/portable/String.hpp>
#include <safedds/serialization/cdr/Alignment.hpp>
#include <safedds/serialization/cdr/Deserializer.hpp>
#include <safedds/serialization/cdr/Serializer.hpp>
#include <safedds/serialization/cdr/XCDRVersion.hpp>
#include <safedds/serialization/RepresentationHeader.hpp>
#include <safedds/portable/SafeCasts.hpp>

#include <SafeDDSGenAux.hpp>
#include <SafeDDSGenUtils.hpp>

#include <array>
#include <vector>
#include <string>
#include <map>


#include "common.hpp"

namespace safe_edge {
    namespace edge {

        // Forward declaration
        struct VehicleEdgeSummarySerialization;

        /*!
         * @brief This struct represents the structure VehicleEdgeSummary defined by the user in the IDL file.
         * @ingroup edge
         */
        struct VehicleEdgeSummary
        {
            using SerializationStruct = VehicleEdgeSummarySerialization;

            static constexpr eprosima::safedds::gen::IDLExtensibilityKind IDL_EXTENSIBILITY = eprosima::safedds::gen::IDLExtensibilityKind::APPENDABLE;

            /// Member header
            safe_edge::common::Header header ;
            /// Member soc_pct
            float soc_pct = 0.0;
            /// Member current_mode
            safe_edge::common::PolicyMode current_mode = safe_edge::common::PolicyMode::POLICY_UNKNOWN;
            /// Member vehicle_health
            safe_edge::common::HealthStatus vehicle_health = safe_edge::common::HealthStatus::HEALTH_UNKNOWN;
            /// Member v2g_ready
            bool v2g_ready = false;

            // Ensure bounds
        };

        struct VehicleEdgeSummarySerialization
        {
            static constexpr uint32_t max_serialized_size()
            {
                // Return the precalculated max_serialized_size plus required:
                // - Representation Header size (+4 B) since it is serialized in the typesupport serialization method
                // - Alignment to 4 B since the  serialization method adds padding
                return eprosima::safedds::memory::align_to<553ULL + 4ULL, 4U>();
            }

            static constexpr uint32_t max_key_serialized_size()
            {
                return 0ULL;
            }

            static eprosima::safedds::ReturnCode serialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const VehicleEdgeSummary& sample)
            {
                using namespace safe_edge::edge;

                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(
                    ser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                    eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                    eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR);



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(0, sample.header) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(1, sample.soc_pct) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(2, sample.current_mode) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(3, sample.vehicle_health) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(4, sample.v2g_ready) : ret;

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;
            }

            static eprosima::safedds::ReturnCode deserialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& deser,
                    VehicleEdgeSummary& sample)
            {
                using namespace safe_edge::edge;

                // Store the values of the external members in auxiliary variables

                sample = {};

                // Restore the values of the external members

                const eprosima::safedds::gen::EncodingAlgorithm encoding =
                    deser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                        eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                        eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR;

                return deser.deserialize_type(encoding,
                [&sample](eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& inner_deser, const uint32_t id) -> eprosima::safedds::ReturnCode
                {
                    eprosima::safedds::ReturnCode ret_value = eprosima::safedds::ReturnCode::OK;
                    switch (id)
                    {
                            case 0:
                                ret_value = inner_deser.deserialize_member(sample.header);
                                break;

                            case 1:
                                ret_value = inner_deser.deserialize_member(sample.soc_pct);
                                break;

                            case 2:
                                ret_value = inner_deser.deserialize_member(sample.current_mode);
                                break;

                            case 3:
                                ret_value = inner_deser.deserialize_member(sample.vehicle_health);
                                break;

                            case 4:
                                ret_value = inner_deser.deserialize_member(sample.v2g_ready);
                                break;

                    default:
                        ret_value = eprosima::safedds::ReturnCode::UNIMPLEMENTED;
                        break;
                    }
                    return ret_value;
                });
            }

            static eprosima::safedds::ReturnCode serialize_key(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const VehicleEdgeSummary& sample)
            {
                using namespace safe_edge::edge;


                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR2);



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(0, sample.header) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(1, sample.soc_pct) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(2, sample.current_mode) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(3, sample.vehicle_health) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(4, sample.v2g_ready) : ret;


                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;

            }

            static bool compare(
                    const VehicleEdgeSummary& first,
                    const VehicleEdgeSummary& second)
            {
                using namespace safe_edge::edge;

                bool ret = true;

                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.header, second.header);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.soc_pct, second.soc_pct);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.current_mode, second.current_mode);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.vehicle_health, second.vehicle_health);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.v2g_ready, second.v2g_ready);

                return ret;
            }
        };


        struct VehicleEdgeSummaryTypeSupport :
            public eprosima::safedds::dds::TypedTypeSupport<VehicleEdgeSummary>
        {
            using DataType = VehicleEdgeSummary;

            eprosima::safedds::dds::ReturnCode register_type(
                    eprosima::safedds::dds::DomainParticipant& participant,
                    const eprosima::safedds::memory::IStringView& type_name) noexcept override
            {
                return participant.register_type(*this, type_name);
            }

            const eprosima::safedds::memory::IStringView& get_type_name() const noexcept override
            {
                static constexpr char const* default_name = "safe_edge::edge::VehicleEdgeSummary";
                static const eprosima::safedds::memory::container::StaticString256 typesupport_name(default_name);
                return typesupport_name;
            }

            uint32_t max_serialized_size() const noexcept override
            {
                return VehicleEdgeSummarySerialization::max_serialized_size();
            }

            uint32_t serialized_size(
                    const VehicleEdgeSummary& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == sample_serialized_size(sample, xcdr_version, sample_size))
                {
                    sample_size = eprosima::safedds::memory::align_to(
                        eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() +
                        sample_size, 4);
                }

                return sample_size;
            }

            eprosima::safedds::ReturnCode serialize(
                    const VehicleEdgeSummary& sample,
                    eprosima::safedds::memory::IByteArrayView& buffer,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                eprosima::safedds::ReturnCode ret =
                    (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version) || (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2 == xcdr_version) ?
                    eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    if(eprosima::safedds::portable::MACHINE_ENDIANNESS == eprosima::safedds::platform::Endianness::SAFEDDS_BIG_ENDIAN)
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_BE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_BE;
                    }
                    else
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_LE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_LE;
                    }
                }

                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = sample_serialized_size(sample, xcdr_version, sample_size);
                }

                uint32_t aligned_size = eprosima::safedds::memory::align_to(sample_size, 4);
                uint32_t payload_size = eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() + aligned_size;

                if (eprosima::safedds::ReturnCode::OK == ret && buffer.size() >= payload_size)
                {
                    // Indicate the number of padding bytes in the encapsulation options
                    uint32_t required_padding = aligned_size - sample_size;
                    representation_header.encapsulation_options[1] = static_cast<uint8_t>(required_padding);

                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                    ret = ser_rh.serialize_array(
                        representation_header.encapsulation_kind.data(),
                        eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_KIND_SIZE);

                    if (eprosima::safedds::ReturnCode::OK == ret)
                    {
                        ret = ser_rh.serialize_array(
                            representation_header.encapsulation_options.data(), eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_OPTIONS_SIZE);
                    }

                    if (eprosima::safedds::ReturnCode::OK == ret && sample_size > 0)
                    {
                        eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {
                            &buffer[ser_rh.serializer_used_size()],
                            ser_rh.serializer_remaining_size()
                        };

                        eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(payload_view, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);

                        ret = VehicleEdgeSummarySerialization::serialize(ser, sample);

                        // Add padding
                        for (uint32_t i = 0; (eprosima::safedds::ReturnCode::OK == ret) && (i < required_padding); ++i)
                        {
                            ret = ser.serialize('\0');
                        }
                    }
                }

                return ret;
            }

            eprosima::safedds::ReturnCode deserialize(
                    const eprosima::safedds::memory::IConstByteArrayView& buffer,
                    VehicleEdgeSummary& sample) const noexcept override
            {
                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                eprosima::safedds::serialization::cdr::Deserializer deserializer_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1);
                eprosima::safedds::ReturnCode ret = eprosima::safedds::protocol::rtps::RTPSTypeSupport::deserialize(deserializer_rh, representation_header);

                // Check expected RepresentationHeader type to be valid and supported
                const bool is_cdr_v1 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] <= 0x03U);
                const bool is_cdr_v2 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] >= 0x06U && representation_header.encapsulation_kind[1U] <= 0x0BU);
                ret = (eprosima::safedds::ReturnCode::OK == ret && (is_cdr_v1 || is_cdr_v2)) ? eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                // Skip payload
                eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {nullptr, 0U};
                uint32_t remaining_size = deserializer_rh.deserializer_remaining_size();
                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    uint32_t padding_size = static_cast<uint32_t>(representation_header.encapsulation_options[1] & 0x03);
                    if (remaining_size >= padding_size)
                    {
                        remaining_size -= padding_size;
                        ret = deserializer_rh.deserializer_skip(remaining_size, payload_view);
                    }
                    else
                    {
                        ret = eprosima::safedds::ReturnCode::SERIALIZATION_INVALID_REPRESENTATION;
                    }
                }

                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    // Get received endianness and deserialize payload
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer deserializer(payload_view,
                        representation_header.get_endianness(),
                        is_cdr_v1 ? eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 : eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2);

                    ret = VehicleEdgeSummarySerialization::deserialize(deserializer, sample);
                }

                return ret;
            }

            eprosima::safedds::dds::ReturnCode get_key(
                    const VehicleEdgeSummary& data,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(data);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            eprosima::safedds::dds::ReturnCode get_key_from_payload(
                    const eprosima::safedds::memory::IConstByteArrayView& view,
                    const eprosima::safedds::protocol::PayloadKind& kind,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(view);
                static_cast<void>(kind);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            bool has_keys() const noexcept override
            {
                return false;
            }

        private:

            eprosima::safedds::ReturnCode sample_serialized_size(
                    const VehicleEdgeSummary& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version,
                    uint32_t & serialized_size) const noexcept
            {
                serialized_size = 0;

                // Create a fake serializer to calculate the serialized size
                eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                eprosima::safedds::ReturnCode ret = VehicleEdgeSummarySerialization::serialize(ser, sample);

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    serialized_size = ser.serializer_used_size();
                }

                return ret;
            }

        };



        // Forward declaration
        struct EnergyAdvisorySerialization;

        /*!
         * @brief This struct represents the structure EnergyAdvisory defined by the user in the IDL file.
         * @ingroup edge
         */
        struct EnergyAdvisory
        {
            using SerializationStruct = EnergyAdvisorySerialization;

            static constexpr eprosima::safedds::gen::IDLExtensibilityKind IDL_EXTENSIBILITY = eprosima::safedds::gen::IDLExtensibilityKind::APPENDABLE;

            /// Member header
            safe_edge::common::Header header ;
            /// Member suggested_mode
            safe_edge::common::PolicyMode suggested_mode = safe_edge::common::PolicyMode::POLICY_UNKNOWN;
            /// Member advisory_reason
            std::string advisory_reason ;
            /// Member recommended_charger_id
            int32_t recommended_charger_id = 0;
            /// Member target_soc_pct
            float target_soc_pct = 0.0;

            // Ensure bounds
            static_assert(255 != 0, "advisory_reason shall be bounded or --default_unbounded_max_size shall be used");


        };

        struct EnergyAdvisorySerialization
        {
            static constexpr uint32_t max_serialized_size()
            {
                // Return the precalculated max_serialized_size plus required:
                // - Representation Header size (+4 B) since it is serialized in the typesupport serialization method
                // - Alignment to 4 B since the  serialization method adds padding
                return eprosima::safedds::memory::align_to<812ULL + 4ULL, 4U>();
            }

            static constexpr uint32_t max_key_serialized_size()
            {
                return 0ULL;
            }

            static eprosima::safedds::ReturnCode serialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const EnergyAdvisory& sample)
            {
                using namespace safe_edge::edge;

                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(
                    ser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                    eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                    eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR);

                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.advisory_reason.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(0, sample.header) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(1, sample.suggested_mode) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(2, sample.advisory_reason) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(3, sample.recommended_charger_id) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(4, sample.target_soc_pct) : ret;

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;
            }

            static eprosima::safedds::ReturnCode deserialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& deser,
                    EnergyAdvisory& sample)
            {
                using namespace safe_edge::edge;

                // Store the values of the external members in auxiliary variables

                sample = {};

                // Restore the values of the external members

                const eprosima::safedds::gen::EncodingAlgorithm encoding =
                    deser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                        eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                        eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR;

                return deser.deserialize_type(encoding,
                [&sample](eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& inner_deser, const uint32_t id) -> eprosima::safedds::ReturnCode
                {
                    eprosima::safedds::ReturnCode ret_value = eprosima::safedds::ReturnCode::OK;
                    switch (id)
                    {
                            case 0:
                                ret_value = inner_deser.deserialize_member(sample.header);
                                break;

                            case 1:
                                ret_value = inner_deser.deserialize_member(sample.suggested_mode);
                                break;

                            case 2:
                                ret_value = inner_deser.deserialize_member(sample.advisory_reason);
                                break;

                            case 3:
                                ret_value = inner_deser.deserialize_member(sample.recommended_charger_id);
                                break;

                            case 4:
                                ret_value = inner_deser.deserialize_member(sample.target_soc_pct);
                                break;

                    default:
                        ret_value = eprosima::safedds::ReturnCode::UNIMPLEMENTED;
                        break;
                    }
                    return ret_value;
                });
            }

            static eprosima::safedds::ReturnCode serialize_key(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const EnergyAdvisory& sample)
            {
                using namespace safe_edge::edge;


                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR2);

                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.advisory_reason.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(0, sample.header) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(1, sample.suggested_mode) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(2, sample.advisory_reason) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(3, sample.recommended_charger_id) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(4, sample.target_soc_pct) : ret;


                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;

            }

            static bool compare(
                    const EnergyAdvisory& first,
                    const EnergyAdvisory& second)
            {
                using namespace safe_edge::edge;

                bool ret = true;

                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.header, second.header);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.suggested_mode, second.suggested_mode);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.advisory_reason, second.advisory_reason);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.recommended_charger_id, second.recommended_charger_id);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.target_soc_pct, second.target_soc_pct);

                return ret;
            }
        };


        struct EnergyAdvisoryTypeSupport :
            public eprosima::safedds::dds::TypedTypeSupport<EnergyAdvisory>
        {
            using DataType = EnergyAdvisory;

            eprosima::safedds::dds::ReturnCode register_type(
                    eprosima::safedds::dds::DomainParticipant& participant,
                    const eprosima::safedds::memory::IStringView& type_name) noexcept override
            {
                return participant.register_type(*this, type_name);
            }

            const eprosima::safedds::memory::IStringView& get_type_name() const noexcept override
            {
                static constexpr char const* default_name = "safe_edge::edge::EnergyAdvisory";
                static const eprosima::safedds::memory::container::StaticString256 typesupport_name(default_name);
                return typesupport_name;
            }

            uint32_t max_serialized_size() const noexcept override
            {
                return EnergyAdvisorySerialization::max_serialized_size();
            }

            uint32_t serialized_size(
                    const EnergyAdvisory& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == sample_serialized_size(sample, xcdr_version, sample_size))
                {
                    sample_size = eprosima::safedds::memory::align_to(
                        eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() +
                        sample_size, 4);
                }

                return sample_size;
            }

            eprosima::safedds::ReturnCode serialize(
                    const EnergyAdvisory& sample,
                    eprosima::safedds::memory::IByteArrayView& buffer,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                eprosima::safedds::ReturnCode ret =
                    (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version) || (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2 == xcdr_version) ?
                    eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    if(eprosima::safedds::portable::MACHINE_ENDIANNESS == eprosima::safedds::platform::Endianness::SAFEDDS_BIG_ENDIAN)
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_BE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_BE;
                    }
                    else
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_LE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_LE;
                    }
                }

                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = sample_serialized_size(sample, xcdr_version, sample_size);
                }

                uint32_t aligned_size = eprosima::safedds::memory::align_to(sample_size, 4);
                uint32_t payload_size = eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() + aligned_size;

                if (eprosima::safedds::ReturnCode::OK == ret && buffer.size() >= payload_size)
                {
                    // Indicate the number of padding bytes in the encapsulation options
                    uint32_t required_padding = aligned_size - sample_size;
                    representation_header.encapsulation_options[1] = static_cast<uint8_t>(required_padding);

                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                    ret = ser_rh.serialize_array(
                        representation_header.encapsulation_kind.data(),
                        eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_KIND_SIZE);

                    if (eprosima::safedds::ReturnCode::OK == ret)
                    {
                        ret = ser_rh.serialize_array(
                            representation_header.encapsulation_options.data(), eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_OPTIONS_SIZE);
                    }

                    if (eprosima::safedds::ReturnCode::OK == ret && sample_size > 0)
                    {
                        eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {
                            &buffer[ser_rh.serializer_used_size()],
                            ser_rh.serializer_remaining_size()
                        };

                        eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(payload_view, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);

                        ret = EnergyAdvisorySerialization::serialize(ser, sample);

                        // Add padding
                        for (uint32_t i = 0; (eprosima::safedds::ReturnCode::OK == ret) && (i < required_padding); ++i)
                        {
                            ret = ser.serialize('\0');
                        }
                    }
                }

                return ret;
            }

            eprosima::safedds::ReturnCode deserialize(
                    const eprosima::safedds::memory::IConstByteArrayView& buffer,
                    EnergyAdvisory& sample) const noexcept override
            {
                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                eprosima::safedds::serialization::cdr::Deserializer deserializer_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1);
                eprosima::safedds::ReturnCode ret = eprosima::safedds::protocol::rtps::RTPSTypeSupport::deserialize(deserializer_rh, representation_header);

                // Check expected RepresentationHeader type to be valid and supported
                const bool is_cdr_v1 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] <= 0x03U);
                const bool is_cdr_v2 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] >= 0x06U && representation_header.encapsulation_kind[1U] <= 0x0BU);
                ret = (eprosima::safedds::ReturnCode::OK == ret && (is_cdr_v1 || is_cdr_v2)) ? eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                // Skip payload
                eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {nullptr, 0U};
                uint32_t remaining_size = deserializer_rh.deserializer_remaining_size();
                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    uint32_t padding_size = static_cast<uint32_t>(representation_header.encapsulation_options[1] & 0x03);
                    if (remaining_size >= padding_size)
                    {
                        remaining_size -= padding_size;
                        ret = deserializer_rh.deserializer_skip(remaining_size, payload_view);
                    }
                    else
                    {
                        ret = eprosima::safedds::ReturnCode::SERIALIZATION_INVALID_REPRESENTATION;
                    }
                }

                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    // Get received endianness and deserialize payload
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer deserializer(payload_view,
                        representation_header.get_endianness(),
                        is_cdr_v1 ? eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 : eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2);

                    ret = EnergyAdvisorySerialization::deserialize(deserializer, sample);
                }

                return ret;
            }

            eprosima::safedds::dds::ReturnCode get_key(
                    const EnergyAdvisory& data,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(data);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            eprosima::safedds::dds::ReturnCode get_key_from_payload(
                    const eprosima::safedds::memory::IConstByteArrayView& view,
                    const eprosima::safedds::protocol::PayloadKind& kind,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(view);
                static_cast<void>(kind);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            bool has_keys() const noexcept override
            {
                return false;
            }

        private:

            eprosima::safedds::ReturnCode sample_serialized_size(
                    const EnergyAdvisory& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version,
                    uint32_t & serialized_size) const noexcept
            {
                serialized_size = 0;

                // Create a fake serializer to calculate the serialized size
                eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                eprosima::safedds::ReturnCode ret = EnergyAdvisorySerialization::serialize(ser, sample);

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    serialized_size = ser.serializer_used_size();
                }

                return ret;
            }

        };



        // Forward declaration
        struct EdgeGatewayStatusSerialization;

        /*!
         * @brief This struct represents the structure EdgeGatewayStatus defined by the user in the IDL file.
         * @ingroup edge
         */
        struct EdgeGatewayStatus
        {
            using SerializationStruct = EdgeGatewayStatusSerialization;

            static constexpr eprosima::safedds::gen::IDLExtensibilityKind IDL_EXTENSIBILITY = eprosima::safedds::gen::IDLExtensibilityKind::APPENDABLE;

            /// Member header
            safe_edge::common::Header header ;
            /// Member status
            safe_edge::common::HealthStatus status = safe_edge::common::HealthStatus::HEALTH_UNKNOWN;
            /// Member last_server_sync_ms
            uint64_t last_server_sync_ms = 0;
            /// Member detail
            std::string detail ;

            // Ensure bounds
            static_assert(255 != 0, "detail shall be bounded or --default_unbounded_max_size shall be used");
        };

        struct EdgeGatewayStatusSerialization
        {
            static constexpr uint32_t max_serialized_size()
            {
                // Return the precalculated max_serialized_size plus required:
                // - Representation Header size (+4 B) since it is serialized in the typesupport serialization method
                // - Alignment to 4 B since the  serialization method adds padding
                return eprosima::safedds::memory::align_to<812ULL + 4ULL, 4U>();
            }

            static constexpr uint32_t max_key_serialized_size()
            {
                return 0ULL;
            }

            static eprosima::safedds::ReturnCode serialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const EdgeGatewayStatus& sample)
            {
                using namespace safe_edge::edge;

                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(
                    ser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                    eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                    eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR);

                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.detail.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(0, sample.header) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(1, sample.status) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(2, sample.last_server_sync_ms) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type(3, sample.detail) : ret;

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;
            }

            static eprosima::safedds::ReturnCode deserialize(
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& deser,
                    EdgeGatewayStatus& sample)
            {
                using namespace safe_edge::edge;

                // Store the values of the external members in auxiliary variables

                sample = {};

                // Restore the values of the external members

                const eprosima::safedds::gen::EncodingAlgorithm encoding =
                    deser.get_xcdr_version() == eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 ?
                        eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR :
                        eprosima::safedds::gen::EncodingAlgorithm::DELIMITED_CDR;

                return deser.deserialize_type(encoding,
                [&sample](eprosima::safedds::gen::SafeDDSTypeSupportDeserializer& inner_deser, const uint32_t id) -> eprosima::safedds::ReturnCode
                {
                    eprosima::safedds::ReturnCode ret_value = eprosima::safedds::ReturnCode::OK;
                    switch (id)
                    {
                            case 0:
                                ret_value = inner_deser.deserialize_member(sample.header);
                                break;

                            case 1:
                                ret_value = inner_deser.deserialize_member(sample.status);
                                break;

                            case 2:
                                ret_value = inner_deser.deserialize_member(sample.last_server_sync_ms);
                                break;

                            case 3:
                                ret_value = inner_deser.deserialize_member(sample.detail);
                                break;

                    default:
                        ret_value = eprosima::safedds::ReturnCode::UNIMPLEMENTED;
                        break;
                    }
                    return ret_value;
                });
            }

            static eprosima::safedds::ReturnCode serialize_key(
                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer& ser,
                    const EdgeGatewayStatus& sample)
            {
                using namespace safe_edge::edge;


                eprosima::safedds::gen::EncodingAlgorithm prev_encoding = ser.get_encoding_algorithm();
                eprosima::safedds::ReturnCode ret = ser.set_encoding_algorithm(eprosima::safedds::gen::EncodingAlgorithm::PLAIN_CDR2);

                ret = ((eprosima::safedds::ReturnCode::OK == ret) && (sample.detail.size() <= 255)) ? ret : eprosima::safedds::ReturnCode::ERROR;



                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.begin_serialize_type() : ret;

                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(0, sample.header) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(1, sample.status) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(2, sample.last_server_sync_ms) : ret;
                ret = (eprosima::safedds::ReturnCode::OK == ret) ? ser.serialize_type_key(3, sample.detail) : ret;


                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.end_serialize_type();
                }

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = ser.set_encoding_algorithm(prev_encoding);
                }

                return ret;

            }

            static bool compare(
                    const EdgeGatewayStatus& first,
                    const EdgeGatewayStatus& second)
            {
                using namespace safe_edge::edge;

                bool ret = true;

                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.header, second.header);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.status, second.status);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.last_server_sync_ms, second.last_server_sync_ms);
                ret = ret && eprosima::safedds::gen::SafeDDSTypeSupportComparator::equal(first.detail, second.detail);

                return ret;
            }
        };


        struct EdgeGatewayStatusTypeSupport :
            public eprosima::safedds::dds::TypedTypeSupport<EdgeGatewayStatus>
        {
            using DataType = EdgeGatewayStatus;

            eprosima::safedds::dds::ReturnCode register_type(
                    eprosima::safedds::dds::DomainParticipant& participant,
                    const eprosima::safedds::memory::IStringView& type_name) noexcept override
            {
                return participant.register_type(*this, type_name);
            }

            const eprosima::safedds::memory::IStringView& get_type_name() const noexcept override
            {
                static constexpr char const* default_name = "safe_edge::edge::EdgeGatewayStatus";
                static const eprosima::safedds::memory::container::StaticString256 typesupport_name(default_name);
                return typesupport_name;
            }

            uint32_t max_serialized_size() const noexcept override
            {
                return EdgeGatewayStatusSerialization::max_serialized_size();
            }

            uint32_t serialized_size(
                    const EdgeGatewayStatus& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == sample_serialized_size(sample, xcdr_version, sample_size))
                {
                    sample_size = eprosima::safedds::memory::align_to(
                        eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() +
                        sample_size, 4);
                }

                return sample_size;
            }

            eprosima::safedds::ReturnCode serialize(
                    const EdgeGatewayStatus& sample,
                    eprosima::safedds::memory::IByteArrayView& buffer,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version) const noexcept override
            {
                eprosima::safedds::ReturnCode ret =
                    (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version) || (eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2 == xcdr_version) ?
                    eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    if(eprosima::safedds::portable::MACHINE_ENDIANNESS == eprosima::safedds::platform::Endianness::SAFEDDS_BIG_ENDIAN)
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_BE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_BE;
                    }
                    else
                    {
                        representation_header =
                            eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 == xcdr_version  ?
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_CDR_LE :
                        eprosima::safedds::serialization::REPRESENTATION_HEADER_DELIMITED_CDR_LE;
                    }
                }

                uint32_t sample_size = 0;

                if (eprosima::safedds::ReturnCode::OK == ret)
                {
                    ret = sample_serialized_size(sample, xcdr_version, sample_size);
                }

                uint32_t aligned_size = eprosima::safedds::memory::align_to(sample_size, 4);
                uint32_t payload_size = eprosima::safedds::portable::safe_sizeof<eprosima::safedds::serialization::RepresentationHeader>() + aligned_size;

                if (eprosima::safedds::ReturnCode::OK == ret && buffer.size() >= payload_size)
                {
                    // Indicate the number of padding bytes in the encapsulation options
                    uint32_t required_padding = aligned_size - sample_size;
                    representation_header.encapsulation_options[1] = static_cast<uint8_t>(required_padding);

                    eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                    ret = ser_rh.serialize_array(
                        representation_header.encapsulation_kind.data(),
                        eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_KIND_SIZE);

                    if (eprosima::safedds::ReturnCode::OK == ret)
                    {
                        ret = ser_rh.serialize_array(
                            representation_header.encapsulation_options.data(), eprosima::safedds::serialization::RepresentationHeader::ENCAPSULATION_OPTIONS_SIZE);
                    }

                    if (eprosima::safedds::ReturnCode::OK == ret && sample_size > 0)
                    {
                        eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {
                            &buffer[ser_rh.serializer_used_size()],
                            ser_rh.serializer_remaining_size()
                        };

                        eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(payload_view, eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);

                        ret = EdgeGatewayStatusSerialization::serialize(ser, sample);

                        // Add padding
                        for (uint32_t i = 0; (eprosima::safedds::ReturnCode::OK == ret) && (i < required_padding); ++i)
                        {
                            ret = ser.serialize('\0');
                        }
                    }
                }

                return ret;
            }

            eprosima::safedds::ReturnCode deserialize(
                    const eprosima::safedds::memory::IConstByteArrayView& buffer,
                    EdgeGatewayStatus& sample) const noexcept override
            {
                eprosima::safedds::serialization::RepresentationHeader representation_header{};

                eprosima::safedds::serialization::cdr::Deserializer deserializer_rh(buffer, eprosima::safedds::portable::MACHINE_ENDIANNESS, eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1);
                eprosima::safedds::ReturnCode ret = eprosima::safedds::protocol::rtps::RTPSTypeSupport::deserialize(deserializer_rh, representation_header);

                // Check expected RepresentationHeader type to be valid and supported
                const bool is_cdr_v1 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] <= 0x03U);
                const bool is_cdr_v2 = representation_header.encapsulation_kind[0U] == 0U && (representation_header.encapsulation_kind[1U] >= 0x06U && representation_header.encapsulation_kind[1U] <= 0x0BU);
                ret = (eprosima::safedds::ReturnCode::OK == ret && (is_cdr_v1 || is_cdr_v2)) ? eprosima::safedds::ReturnCode::OK : eprosima::safedds::ReturnCode::ERROR;

                // Skip payload
                eprosima::safedds::memory::byte_array::ByteArrayView payload_view = {nullptr, 0U};
                uint32_t remaining_size = deserializer_rh.deserializer_remaining_size();
                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    uint32_t padding_size = static_cast<uint32_t>(representation_header.encapsulation_options[1] & 0x03);
                    if (remaining_size >= padding_size)
                    {
                        remaining_size -= padding_size;
                        ret = deserializer_rh.deserializer_skip(remaining_size, payload_view);
                    }
                    else
                    {
                        ret = eprosima::safedds::ReturnCode::SERIALIZATION_INVALID_REPRESENTATION;
                    }
                }

                if (eprosima::safedds::ReturnCode::OK == ret && remaining_size > 0)
                {
                    // Get received endianness and deserialize payload
                    eprosima::safedds::gen::SafeDDSTypeSupportDeserializer deserializer(payload_view,
                        representation_header.get_endianness(),
                        is_cdr_v1 ? eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV1 : eprosima::safedds::serialization::cdr::XCDRVersion::XCDRV2);

                    ret = EdgeGatewayStatusSerialization::deserialize(deserializer, sample);
                }

                return ret;
            }

            eprosima::safedds::dds::ReturnCode get_key(
                    const EdgeGatewayStatus& data,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(data);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            eprosima::safedds::dds::ReturnCode get_key_from_payload(
                    const eprosima::safedds::memory::IConstByteArrayView& view,
                    const eprosima::safedds::protocol::PayloadKind& kind,
                    eprosima::safedds::dds::KeyHash& key_hash) const noexcept override
            {
                key_hash = {};

                static_cast<void>(view);
                static_cast<void>(kind);

                return eprosima::safedds::dds::ReturnCode::ILLEGAL_OPERATION;
            }

            bool has_keys() const noexcept override
            {
                return false;
            }

        private:

            eprosima::safedds::ReturnCode sample_serialized_size(
                    const EdgeGatewayStatus& sample,
                    eprosima::safedds::serialization::cdr::XCDRVersion xcdr_version,
                    uint32_t & serialized_size) const noexcept
            {
                serialized_size = 0;

                // Create a fake serializer to calculate the serialized size
                eprosima::safedds::gen::SafeDDSTypeSupportSerializer ser(eprosima::safedds::portable::MACHINE_ENDIANNESS, xcdr_version);
                eprosima::safedds::ReturnCode ret = EdgeGatewayStatusSerialization::serialize(ser, sample);

                if(eprosima::safedds::ReturnCode::OK == ret)
                {
                    serialized_size = ser.serializer_used_size();
                }

                return ret;
            }

        };


    } // namespace edge
} // namespace safe_edge

#endif  // SAFEDDS_GENERATED__SAFE_EDGE_EDGE_EDGE_HPP