// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file commonTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "commonTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "common.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace safe_edge {
namespace common {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Header_type_identifier(
        TypeIdentifierPair& type_ids_Header)
{

    ReturnCode_t return_code_Header {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Header =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::common::Header", type_ids_Header);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Header)
    {
        StructTypeFlag struct_flags_Header = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Header = "safe_edge::common::Header";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Header;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Header;
        CompleteTypeDetail detail_Header = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Header, ann_custom_Header, type_name_Header.to_string());
        CompleteStructHeader header_Header;
        header_Header = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Header);
        CompleteStructMemberSeq member_seq_Header;
        {
            TypeIdentifierPair type_ids_source;
            ReturnCode_t return_code_source {eprosima::fastdds::dds::RETCODE_OK};
            return_code_source =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_source);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_source)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_source))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_source = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_source = 0x00000000;
            bool common_source_ec {false};
            CommonStructMember common_source {TypeObjectUtils::build_common_struct_member(member_id_source, member_flags_source, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_source, common_source_ec))};
            if (!common_source_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure source member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_source = "source";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_source;
            ann_custom_Header.reset();
            CompleteMemberDetail detail_source = TypeObjectUtils::build_complete_member_detail(name_source, member_ann_builtin_source, ann_custom_Header);
            CompleteStructMember member_source = TypeObjectUtils::build_complete_struct_member(common_source, detail_source);
            TypeObjectUtils::add_complete_struct_member(member_seq_Header, member_source);
        }
        {
            TypeIdentifierPair type_ids_timestamp_ms;
            ReturnCode_t return_code_timestamp_ms {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp_ms =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_timestamp_ms);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp_ms)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp_ms Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp_ms = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp_ms = 0x00000001;
            bool common_timestamp_ms_ec {false};
            CommonStructMember common_timestamp_ms {TypeObjectUtils::build_common_struct_member(member_id_timestamp_ms, member_flags_timestamp_ms, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp_ms, common_timestamp_ms_ec))};
            if (!common_timestamp_ms_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp_ms member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp_ms = "timestamp_ms";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp_ms;
            ann_custom_Header.reset();
            CompleteMemberDetail detail_timestamp_ms = TypeObjectUtils::build_complete_member_detail(name_timestamp_ms, member_ann_builtin_timestamp_ms, ann_custom_Header);
            CompleteStructMember member_timestamp_ms = TypeObjectUtils::build_complete_struct_member(common_timestamp_ms, detail_timestamp_ms);
            TypeObjectUtils::add_complete_struct_member(member_seq_Header, member_timestamp_ms);
        }
        {
            TypeIdentifierPair type_ids_trace_id;
            ReturnCode_t return_code_trace_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_trace_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_trace_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_trace_id)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_trace_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_trace_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_trace_id = 0x00000002;
            bool common_trace_id_ec {false};
            CommonStructMember common_trace_id {TypeObjectUtils::build_common_struct_member(member_id_trace_id, member_flags_trace_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_trace_id, common_trace_id_ec))};
            if (!common_trace_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure trace_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_trace_id = "trace_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_trace_id;
            ann_custom_Header.reset();
            CompleteMemberDetail detail_trace_id = TypeObjectUtils::build_complete_member_detail(name_trace_id, member_ann_builtin_trace_id, ann_custom_Header);
            CompleteStructMember member_trace_id = TypeObjectUtils::build_complete_struct_member(common_trace_id, detail_trace_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_Header, member_trace_id);
        }
        CompleteStructType struct_type_Header = TypeObjectUtils::build_complete_struct_type(struct_flags_Header, header_Header, member_seq_Header);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Header, type_name_Header.to_string(), type_ids_Header))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::common::Header already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_GeoPoint_type_identifier(
        TypeIdentifierPair& type_ids_GeoPoint)
{

    ReturnCode_t return_code_GeoPoint {eprosima::fastdds::dds::RETCODE_OK};
    return_code_GeoPoint =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::common::GeoPoint", type_ids_GeoPoint);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_GeoPoint)
    {
        StructTypeFlag struct_flags_GeoPoint = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_GeoPoint = "safe_edge::common::GeoPoint";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_GeoPoint;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_GeoPoint;
        CompleteTypeDetail detail_GeoPoint = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_GeoPoint, ann_custom_GeoPoint, type_name_GeoPoint.to_string());
        CompleteStructHeader header_GeoPoint;
        header_GeoPoint = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_GeoPoint);
        CompleteStructMemberSeq member_seq_GeoPoint;
        {
            TypeIdentifierPair type_ids_latitude;
            ReturnCode_t return_code_latitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_latitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_latitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_latitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "latitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_latitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_latitude = 0x00000000;
            bool common_latitude_ec {false};
            CommonStructMember common_latitude {TypeObjectUtils::build_common_struct_member(member_id_latitude, member_flags_latitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_latitude, common_latitude_ec))};
            if (!common_latitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure latitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_latitude = "latitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_latitude;
            ann_custom_GeoPoint.reset();
            CompleteMemberDetail detail_latitude = TypeObjectUtils::build_complete_member_detail(name_latitude, member_ann_builtin_latitude, ann_custom_GeoPoint);
            CompleteStructMember member_latitude = TypeObjectUtils::build_complete_struct_member(common_latitude, detail_latitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_GeoPoint, member_latitude);
        }
        {
            TypeIdentifierPair type_ids_longitude;
            ReturnCode_t return_code_longitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_longitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_longitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_longitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "longitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_longitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_longitude = 0x00000001;
            bool common_longitude_ec {false};
            CommonStructMember common_longitude {TypeObjectUtils::build_common_struct_member(member_id_longitude, member_flags_longitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_longitude, common_longitude_ec))};
            if (!common_longitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure longitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_longitude = "longitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_longitude;
            ann_custom_GeoPoint.reset();
            CompleteMemberDetail detail_longitude = TypeObjectUtils::build_complete_member_detail(name_longitude, member_ann_builtin_longitude, ann_custom_GeoPoint);
            CompleteStructMember member_longitude = TypeObjectUtils::build_complete_struct_member(common_longitude, detail_longitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_GeoPoint, member_longitude);
        }
        CompleteStructType struct_type_GeoPoint = TypeObjectUtils::build_complete_struct_type(struct_flags_GeoPoint, header_GeoPoint, member_seq_GeoPoint);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_GeoPoint, type_name_GeoPoint.to_string(), type_ids_GeoPoint))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::common::GeoPoint already registered in TypeObjectRegistry for a different type.");
        }
    }
}void register_HealthStatus_type_identifier(
        TypeIdentifierPair& type_ids_HealthStatus)
{
    ReturnCode_t return_code_HealthStatus {eprosima::fastdds::dds::RETCODE_OK};
    return_code_HealthStatus =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::common::HealthStatus", type_ids_HealthStatus);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_HealthStatus)
    {
        EnumTypeFlag enum_flags_HealthStatus = 0;
        BitBound bit_bound_HealthStatus = 32;
        CommonEnumeratedHeader common_HealthStatus = TypeObjectUtils::build_common_enumerated_header(bit_bound_HealthStatus);
        QualifiedTypeName type_name_HealthStatus = "safe_edge::common::HealthStatus";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_HealthStatus;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_HealthStatus;
        CompleteTypeDetail detail_HealthStatus = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_HealthStatus, ann_custom_HealthStatus, type_name_HealthStatus.to_string());
        CompleteEnumeratedHeader header_HealthStatus = TypeObjectUtils::build_complete_enumerated_header(common_HealthStatus, detail_HealthStatus);
        CompleteEnumeratedLiteralSeq literal_seq_HealthStatus;
        {
            EnumeratedLiteralFlag flags_HEALTH_UNKNOWN = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_HEALTH_UNKNOWN = TypeObjectUtils::build_common_enumerated_literal(0, flags_HEALTH_UNKNOWN);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_HEALTH_UNKNOWN;
            ann_custom_HealthStatus.reset();
            MemberName name_HEALTH_UNKNOWN = "HEALTH_UNKNOWN";
            CompleteMemberDetail detail_HEALTH_UNKNOWN = TypeObjectUtils::build_complete_member_detail(name_HEALTH_UNKNOWN, member_ann_builtin_HEALTH_UNKNOWN, ann_custom_HealthStatus);
            CompleteEnumeratedLiteral literal_HEALTH_UNKNOWN = TypeObjectUtils::build_complete_enumerated_literal(common_HEALTH_UNKNOWN, detail_HEALTH_UNKNOWN);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_HealthStatus, literal_HEALTH_UNKNOWN);
        }
        {
            EnumeratedLiteralFlag flags_HEALTH_OK = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_HEALTH_OK = TypeObjectUtils::build_common_enumerated_literal(1, flags_HEALTH_OK);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_HEALTH_OK;
            ann_custom_HealthStatus.reset();
            MemberName name_HEALTH_OK = "HEALTH_OK";
            CompleteMemberDetail detail_HEALTH_OK = TypeObjectUtils::build_complete_member_detail(name_HEALTH_OK, member_ann_builtin_HEALTH_OK, ann_custom_HealthStatus);
            CompleteEnumeratedLiteral literal_HEALTH_OK = TypeObjectUtils::build_complete_enumerated_literal(common_HEALTH_OK, detail_HEALTH_OK);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_HealthStatus, literal_HEALTH_OK);
        }
        {
            EnumeratedLiteralFlag flags_HEALTH_DEGRADED = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_HEALTH_DEGRADED = TypeObjectUtils::build_common_enumerated_literal(2, flags_HEALTH_DEGRADED);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_HEALTH_DEGRADED;
            ann_custom_HealthStatus.reset();
            MemberName name_HEALTH_DEGRADED = "HEALTH_DEGRADED";
            CompleteMemberDetail detail_HEALTH_DEGRADED = TypeObjectUtils::build_complete_member_detail(name_HEALTH_DEGRADED, member_ann_builtin_HEALTH_DEGRADED, ann_custom_HealthStatus);
            CompleteEnumeratedLiteral literal_HEALTH_DEGRADED = TypeObjectUtils::build_complete_enumerated_literal(common_HEALTH_DEGRADED, detail_HEALTH_DEGRADED);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_HealthStatus, literal_HEALTH_DEGRADED);
        }
        {
            EnumeratedLiteralFlag flags_HEALTH_ERROR = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_HEALTH_ERROR = TypeObjectUtils::build_common_enumerated_literal(3, flags_HEALTH_ERROR);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_HEALTH_ERROR;
            ann_custom_HealthStatus.reset();
            MemberName name_HEALTH_ERROR = "HEALTH_ERROR";
            CompleteMemberDetail detail_HEALTH_ERROR = TypeObjectUtils::build_complete_member_detail(name_HEALTH_ERROR, member_ann_builtin_HEALTH_ERROR, ann_custom_HealthStatus);
            CompleteEnumeratedLiteral literal_HEALTH_ERROR = TypeObjectUtils::build_complete_enumerated_literal(common_HEALTH_ERROR, detail_HEALTH_ERROR);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_HealthStatus, literal_HEALTH_ERROR);
        }
        CompleteEnumeratedType enumerated_type_HealthStatus = TypeObjectUtils::build_complete_enumerated_type(enum_flags_HealthStatus, header_HealthStatus,
                literal_seq_HealthStatus);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_enumerated_type_object(enumerated_type_HealthStatus, type_name_HealthStatus.to_string(), type_ids_HealthStatus))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "safe_edge::common::HealthStatus already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ServiceHeartbeat_type_identifier(
        TypeIdentifierPair& type_ids_ServiceHeartbeat)
{

    ReturnCode_t return_code_ServiceHeartbeat {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ServiceHeartbeat =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::common::ServiceHeartbeat", type_ids_ServiceHeartbeat);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ServiceHeartbeat)
    {
        StructTypeFlag struct_flags_ServiceHeartbeat = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_ServiceHeartbeat = "safe_edge::common::ServiceHeartbeat";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ServiceHeartbeat;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ServiceHeartbeat;
        CompleteTypeDetail detail_ServiceHeartbeat = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ServiceHeartbeat, ann_custom_ServiceHeartbeat, type_name_ServiceHeartbeat.to_string());
        CompleteStructHeader header_ServiceHeartbeat;
        header_ServiceHeartbeat = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ServiceHeartbeat);
        CompleteStructMemberSeq member_seq_ServiceHeartbeat;
        {
            TypeIdentifierPair type_ids_header_st;
            ReturnCode_t return_code_header_st {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header_st =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::common::Header", type_ids_header_st);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header_st)
            {
                ::safe_edge::common::register_Header_type_identifier(type_ids_header_st);
            }
            StructMemberFlag member_flags_header_st = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header_st = 0x00000000;
            bool common_header_st_ec {false};
            CommonStructMember common_header_st {TypeObjectUtils::build_common_struct_member(member_id_header_st, member_flags_header_st, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header_st, common_header_st_ec))};
            if (!common_header_st_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header_st member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header_st = "header_st";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header_st;
            ann_custom_ServiceHeartbeat.reset();
            CompleteMemberDetail detail_header_st = TypeObjectUtils::build_complete_member_detail(name_header_st, member_ann_builtin_header_st, ann_custom_ServiceHeartbeat);
            CompleteStructMember member_header_st = TypeObjectUtils::build_complete_struct_member(common_header_st, detail_header_st);
            TypeObjectUtils::add_complete_struct_member(member_seq_ServiceHeartbeat, member_header_st);
        }
        {
            TypeIdentifierPair type_ids_service_name;
            ReturnCode_t return_code_service_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_service_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_service_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_service_name)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_service_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_service_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_service_name = 0x00000001;
            bool common_service_name_ec {false};
            CommonStructMember common_service_name {TypeObjectUtils::build_common_struct_member(member_id_service_name, member_flags_service_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_service_name, common_service_name_ec))};
            if (!common_service_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure service_name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_service_name = "service_name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_service_name;
            ann_custom_ServiceHeartbeat.reset();
            CompleteMemberDetail detail_service_name = TypeObjectUtils::build_complete_member_detail(name_service_name, member_ann_builtin_service_name, ann_custom_ServiceHeartbeat);
            CompleteStructMember member_service_name = TypeObjectUtils::build_complete_struct_member(common_service_name, detail_service_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_ServiceHeartbeat, member_service_name);
        }
        {
            TypeIdentifierPair type_ids_status;
            ReturnCode_t return_code_status {eprosima::fastdds::dds::RETCODE_OK};
            return_code_status =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::common::HealthStatus", type_ids_status);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_status)
            {
                ::safe_edge::common::register_HealthStatus_type_identifier(type_ids_status);
            }
            StructMemberFlag member_flags_status = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_status = 0x00000002;
            bool common_status_ec {false};
            CommonStructMember common_status {TypeObjectUtils::build_common_struct_member(member_id_status, member_flags_status, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_status, common_status_ec))};
            if (!common_status_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure status member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_status = "status";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_status;
            ann_custom_ServiceHeartbeat.reset();
            CompleteMemberDetail detail_status = TypeObjectUtils::build_complete_member_detail(name_status, member_ann_builtin_status, ann_custom_ServiceHeartbeat);
            CompleteStructMember member_status = TypeObjectUtils::build_complete_struct_member(common_status, detail_status);
            TypeObjectUtils::add_complete_struct_member(member_seq_ServiceHeartbeat, member_status);
        }
        {
            TypeIdentifierPair type_ids_detail;
            ReturnCode_t return_code_detail {eprosima::fastdds::dds::RETCODE_OK};
            return_code_detail =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_detail);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_detail)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_detail))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_detail = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_detail = 0x00000003;
            bool common_detail_ec {false};
            CommonStructMember common_detail {TypeObjectUtils::build_common_struct_member(member_id_detail, member_flags_detail, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_detail, common_detail_ec))};
            if (!common_detail_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure detail member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_detail = "detail";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_detail;
            ann_custom_ServiceHeartbeat.reset();
            CompleteMemberDetail detail_detail = TypeObjectUtils::build_complete_member_detail(name_detail, member_ann_builtin_detail, ann_custom_ServiceHeartbeat);
            CompleteStructMember member_detail = TypeObjectUtils::build_complete_struct_member(common_detail, detail_detail);
            TypeObjectUtils::add_complete_struct_member(member_seq_ServiceHeartbeat, member_detail);
        }
        CompleteStructType struct_type_ServiceHeartbeat = TypeObjectUtils::build_complete_struct_type(struct_flags_ServiceHeartbeat, header_ServiceHeartbeat, member_seq_ServiceHeartbeat);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ServiceHeartbeat, type_name_ServiceHeartbeat.to_string(), type_ids_ServiceHeartbeat))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::common::ServiceHeartbeat already registered in TypeObjectRegistry for a different type.");
        }
    }
}void register_PolicyMode_type_identifier(
        TypeIdentifierPair& type_ids_PolicyMode)
{
    ReturnCode_t return_code_PolicyMode {eprosima::fastdds::dds::RETCODE_OK};
    return_code_PolicyMode =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::common::PolicyMode", type_ids_PolicyMode);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_PolicyMode)
    {
        EnumTypeFlag enum_flags_PolicyMode = 0;
        BitBound bit_bound_PolicyMode = 32;
        CommonEnumeratedHeader common_PolicyMode = TypeObjectUtils::build_common_enumerated_header(bit_bound_PolicyMode);
        QualifiedTypeName type_name_PolicyMode = "safe_edge::common::PolicyMode";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_PolicyMode;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_PolicyMode;
        CompleteTypeDetail detail_PolicyMode = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_PolicyMode, ann_custom_PolicyMode, type_name_PolicyMode.to_string());
        CompleteEnumeratedHeader header_PolicyMode = TypeObjectUtils::build_complete_enumerated_header(common_PolicyMode, detail_PolicyMode);
        CompleteEnumeratedLiteralSeq literal_seq_PolicyMode;
        {
            EnumeratedLiteralFlag flags_POLICY_UNKNOWN = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_POLICY_UNKNOWN = TypeObjectUtils::build_common_enumerated_literal(0, flags_POLICY_UNKNOWN);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_POLICY_UNKNOWN;
            ann_custom_PolicyMode.reset();
            MemberName name_POLICY_UNKNOWN = "POLICY_UNKNOWN";
            CompleteMemberDetail detail_POLICY_UNKNOWN = TypeObjectUtils::build_complete_member_detail(name_POLICY_UNKNOWN, member_ann_builtin_POLICY_UNKNOWN, ann_custom_PolicyMode);
            CompleteEnumeratedLiteral literal_POLICY_UNKNOWN = TypeObjectUtils::build_complete_enumerated_literal(common_POLICY_UNKNOWN, detail_POLICY_UNKNOWN);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_PolicyMode, literal_POLICY_UNKNOWN);
        }
        {
            EnumeratedLiteralFlag flags_POLICY_NOMINAL = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_POLICY_NOMINAL = TypeObjectUtils::build_common_enumerated_literal(1, flags_POLICY_NOMINAL);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_POLICY_NOMINAL;
            ann_custom_PolicyMode.reset();
            MemberName name_POLICY_NOMINAL = "POLICY_NOMINAL";
            CompleteMemberDetail detail_POLICY_NOMINAL = TypeObjectUtils::build_complete_member_detail(name_POLICY_NOMINAL, member_ann_builtin_POLICY_NOMINAL, ann_custom_PolicyMode);
            CompleteEnumeratedLiteral literal_POLICY_NOMINAL = TypeObjectUtils::build_complete_enumerated_literal(common_POLICY_NOMINAL, detail_POLICY_NOMINAL);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_PolicyMode, literal_POLICY_NOMINAL);
        }
        {
            EnumeratedLiteralFlag flags_POLICY_LOW_SOC = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_POLICY_LOW_SOC = TypeObjectUtils::build_common_enumerated_literal(2, flags_POLICY_LOW_SOC);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_POLICY_LOW_SOC;
            ann_custom_PolicyMode.reset();
            MemberName name_POLICY_LOW_SOC = "POLICY_LOW_SOC";
            CompleteMemberDetail detail_POLICY_LOW_SOC = TypeObjectUtils::build_complete_member_detail(name_POLICY_LOW_SOC, member_ann_builtin_POLICY_LOW_SOC, ann_custom_PolicyMode);
            CompleteEnumeratedLiteral literal_POLICY_LOW_SOC = TypeObjectUtils::build_complete_enumerated_literal(common_POLICY_LOW_SOC, detail_POLICY_LOW_SOC);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_PolicyMode, literal_POLICY_LOW_SOC);
        }
        {
            EnumeratedLiteralFlag flags_POLICY_EDGE_AUTONOMOUS = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_POLICY_EDGE_AUTONOMOUS = TypeObjectUtils::build_common_enumerated_literal(3, flags_POLICY_EDGE_AUTONOMOUS);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_POLICY_EDGE_AUTONOMOUS;
            ann_custom_PolicyMode.reset();
            MemberName name_POLICY_EDGE_AUTONOMOUS = "POLICY_EDGE_AUTONOMOUS";
            CompleteMemberDetail detail_POLICY_EDGE_AUTONOMOUS = TypeObjectUtils::build_complete_member_detail(name_POLICY_EDGE_AUTONOMOUS, member_ann_builtin_POLICY_EDGE_AUTONOMOUS, ann_custom_PolicyMode);
            CompleteEnumeratedLiteral literal_POLICY_EDGE_AUTONOMOUS = TypeObjectUtils::build_complete_enumerated_literal(common_POLICY_EDGE_AUTONOMOUS, detail_POLICY_EDGE_AUTONOMOUS);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_PolicyMode, literal_POLICY_EDGE_AUTONOMOUS);
        }
        {
            EnumeratedLiteralFlag flags_POLICY_DEGRADED_SERVER_DOWN = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_POLICY_DEGRADED_SERVER_DOWN = TypeObjectUtils::build_common_enumerated_literal(4, flags_POLICY_DEGRADED_SERVER_DOWN);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_POLICY_DEGRADED_SERVER_DOWN;
            ann_custom_PolicyMode.reset();
            MemberName name_POLICY_DEGRADED_SERVER_DOWN = "POLICY_DEGRADED_SERVER_DOWN";
            CompleteMemberDetail detail_POLICY_DEGRADED_SERVER_DOWN = TypeObjectUtils::build_complete_member_detail(name_POLICY_DEGRADED_SERVER_DOWN, member_ann_builtin_POLICY_DEGRADED_SERVER_DOWN, ann_custom_PolicyMode);
            CompleteEnumeratedLiteral literal_POLICY_DEGRADED_SERVER_DOWN = TypeObjectUtils::build_complete_enumerated_literal(common_POLICY_DEGRADED_SERVER_DOWN, detail_POLICY_DEGRADED_SERVER_DOWN);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_PolicyMode, literal_POLICY_DEGRADED_SERVER_DOWN);
        }
        {
            EnumeratedLiteralFlag flags_POLICY_DEGRADED_COMPLETE = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_POLICY_DEGRADED_COMPLETE = TypeObjectUtils::build_common_enumerated_literal(5, flags_POLICY_DEGRADED_COMPLETE);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_POLICY_DEGRADED_COMPLETE;
            ann_custom_PolicyMode.reset();
            MemberName name_POLICY_DEGRADED_COMPLETE = "POLICY_DEGRADED_COMPLETE";
            CompleteMemberDetail detail_POLICY_DEGRADED_COMPLETE = TypeObjectUtils::build_complete_member_detail(name_POLICY_DEGRADED_COMPLETE, member_ann_builtin_POLICY_DEGRADED_COMPLETE, ann_custom_PolicyMode);
            CompleteEnumeratedLiteral literal_POLICY_DEGRADED_COMPLETE = TypeObjectUtils::build_complete_enumerated_literal(common_POLICY_DEGRADED_COMPLETE, detail_POLICY_DEGRADED_COMPLETE);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_PolicyMode, literal_POLICY_DEGRADED_COMPLETE);
        }
        CompleteEnumeratedType enumerated_type_PolicyMode = TypeObjectUtils::build_complete_enumerated_type(enum_flags_PolicyMode, header_PolicyMode,
                literal_seq_PolicyMode);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_enumerated_type_object(enumerated_type_PolicyMode, type_name_PolicyMode.to_string(), type_ids_PolicyMode))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "safe_edge::common::PolicyMode already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace common

} // namespace safe_edge

