// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file common.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__SAFE_EDGE_COMMON_COMMON_HPP
#define FAST_DDS_GENERATED__SAFE_EDGE_COMMON_COMMON_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(COMMON_SOURCE)
#define COMMON_DllAPI __declspec( dllexport )
#else
#define COMMON_DllAPI __declspec( dllimport )
#endif // COMMON_SOURCE
#else
#define COMMON_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define COMMON_DllAPI
#endif // _WIN32

namespace safe_edge {

namespace common {

/*!
 * @brief This class represents the structure Header defined by the user in the IDL file.
 * @ingroup common
 */
class Header
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Header()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Header()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Header that will be copied.
     */
    eProsima_user_DllExport Header(
            const Header& x)
    {
                    m_source = x.m_source;

                    m_timestamp_ms = x.m_timestamp_ms;

                    m_trace_id = x.m_trace_id;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Header that will be copied.
     */
    eProsima_user_DllExport Header(
            Header&& x) noexcept
    {
        m_source = std::move(x.m_source);
        m_timestamp_ms = x.m_timestamp_ms;
        m_trace_id = std::move(x.m_trace_id);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Header that will be copied.
     */
    eProsima_user_DllExport Header& operator =(
            const Header& x)
    {

                    m_source = x.m_source;

                    m_timestamp_ms = x.m_timestamp_ms;

                    m_trace_id = x.m_trace_id;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Header that will be copied.
     */
    eProsima_user_DllExport Header& operator =(
            Header&& x) noexcept
    {

        m_source = std::move(x.m_source);
        m_timestamp_ms = x.m_timestamp_ms;
        m_trace_id = std::move(x.m_trace_id);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Header object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Header& x) const
    {
        return (m_source == x.m_source &&
           m_timestamp_ms == x.m_timestamp_ms &&
           m_trace_id == x.m_trace_id);
    }

    /*!
     * @brief Comparison operator.
     * @param x Header object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Header& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member source
     * @param _source New value to be copied in member source
     */
    eProsima_user_DllExport void source(
            const std::string& _source)
    {
        m_source = _source;
    }

    /*!
     * @brief This function moves the value in member source
     * @param _source New value to be moved in member source
     */
    eProsima_user_DllExport void source(
            std::string&& _source)
    {
        m_source = std::move(_source);
    }

    /*!
     * @brief This function returns a constant reference to member source
     * @return Constant reference to member source
     */
    eProsima_user_DllExport const std::string& source() const
    {
        return m_source;
    }

    /*!
     * @brief This function returns a reference to member source
     * @return Reference to member source
     */
    eProsima_user_DllExport std::string& source()
    {
        return m_source;
    }


    /*!
     * @brief This function sets a value in member timestamp_ms
     * @param _timestamp_ms New value for member timestamp_ms
     */
    eProsima_user_DllExport void timestamp_ms(
            uint64_t _timestamp_ms)
    {
        m_timestamp_ms = _timestamp_ms;
    }

    /*!
     * @brief This function returns the value of member timestamp_ms
     * @return Value of member timestamp_ms
     */
    eProsima_user_DllExport uint64_t timestamp_ms() const
    {
        return m_timestamp_ms;
    }

    /*!
     * @brief This function returns a reference to member timestamp_ms
     * @return Reference to member timestamp_ms
     */
    eProsima_user_DllExport uint64_t& timestamp_ms()
    {
        return m_timestamp_ms;
    }


    /*!
     * @brief This function copies the value in member trace_id
     * @param _trace_id New value to be copied in member trace_id
     */
    eProsima_user_DllExport void trace_id(
            const std::string& _trace_id)
    {
        m_trace_id = _trace_id;
    }

    /*!
     * @brief This function moves the value in member trace_id
     * @param _trace_id New value to be moved in member trace_id
     */
    eProsima_user_DllExport void trace_id(
            std::string&& _trace_id)
    {
        m_trace_id = std::move(_trace_id);
    }

    /*!
     * @brief This function returns a constant reference to member trace_id
     * @return Constant reference to member trace_id
     */
    eProsima_user_DllExport const std::string& trace_id() const
    {
        return m_trace_id;
    }

    /*!
     * @brief This function returns a reference to member trace_id
     * @return Reference to member trace_id
     */
    eProsima_user_DllExport std::string& trace_id()
    {
        return m_trace_id;
    }



private:

    std::string m_source;
    uint64_t m_timestamp_ms{0};
    std::string m_trace_id;

};
/*!
 * @brief This class represents the structure GeoPoint defined by the user in the IDL file.
 * @ingroup common
 */
class GeoPoint
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GeoPoint()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GeoPoint()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GeoPoint that will be copied.
     */
    eProsima_user_DllExport GeoPoint(
            const GeoPoint& x)
    {
                    m_latitude = x.m_latitude;

                    m_longitude = x.m_longitude;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GeoPoint that will be copied.
     */
    eProsima_user_DllExport GeoPoint(
            GeoPoint&& x) noexcept
    {
        m_latitude = x.m_latitude;
        m_longitude = x.m_longitude;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GeoPoint that will be copied.
     */
    eProsima_user_DllExport GeoPoint& operator =(
            const GeoPoint& x)
    {

                    m_latitude = x.m_latitude;

                    m_longitude = x.m_longitude;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GeoPoint that will be copied.
     */
    eProsima_user_DllExport GeoPoint& operator =(
            GeoPoint&& x) noexcept
    {

        m_latitude = x.m_latitude;
        m_longitude = x.m_longitude;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x GeoPoint object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GeoPoint& x) const
    {
        return (m_latitude == x.m_latitude &&
           m_longitude == x.m_longitude);
    }

    /*!
     * @brief Comparison operator.
     * @param x GeoPoint object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GeoPoint& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member latitude
     * @param _latitude New value for member latitude
     */
    eProsima_user_DllExport void latitude(
            double _latitude)
    {
        m_latitude = _latitude;
    }

    /*!
     * @brief This function returns the value of member latitude
     * @return Value of member latitude
     */
    eProsima_user_DllExport double latitude() const
    {
        return m_latitude;
    }

    /*!
     * @brief This function returns a reference to member latitude
     * @return Reference to member latitude
     */
    eProsima_user_DllExport double& latitude()
    {
        return m_latitude;
    }


    /*!
     * @brief This function sets a value in member longitude
     * @param _longitude New value for member longitude
     */
    eProsima_user_DllExport void longitude(
            double _longitude)
    {
        m_longitude = _longitude;
    }

    /*!
     * @brief This function returns the value of member longitude
     * @return Value of member longitude
     */
    eProsima_user_DllExport double longitude() const
    {
        return m_longitude;
    }

    /*!
     * @brief This function returns a reference to member longitude
     * @return Reference to member longitude
     */
    eProsima_user_DllExport double& longitude()
    {
        return m_longitude;
    }



private:

    double m_latitude{0.0};
    double m_longitude{0.0};

};
/*!
 * @brief This class represents the enumeration HealthStatus defined by the user in the IDL file.
 * @ingroup common
 */
enum class HealthStatus : int32_t
{
    HEALTH_UNKNOWN,
    HEALTH_OK,
    HEALTH_DEGRADED,
    HEALTH_ERROR
};
/*!
 * @brief This class represents the structure ServiceHeartbeat defined by the user in the IDL file.
 * @ingroup common
 */
class ServiceHeartbeat
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ServiceHeartbeat()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ServiceHeartbeat()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ServiceHeartbeat that will be copied.
     */
    eProsima_user_DllExport ServiceHeartbeat(
            const ServiceHeartbeat& x)
    {
                    m_header_st = x.m_header_st;

                    m_service_name = x.m_service_name;

                    m_status = x.m_status;

                    m_detail = x.m_detail;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ServiceHeartbeat that will be copied.
     */
    eProsima_user_DllExport ServiceHeartbeat(
            ServiceHeartbeat&& x) noexcept
    {
        m_header_st = std::move(x.m_header_st);
        m_service_name = std::move(x.m_service_name);
        m_status = x.m_status;
        m_detail = std::move(x.m_detail);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ServiceHeartbeat that will be copied.
     */
    eProsima_user_DllExport ServiceHeartbeat& operator =(
            const ServiceHeartbeat& x)
    {

                    m_header_st = x.m_header_st;

                    m_service_name = x.m_service_name;

                    m_status = x.m_status;

                    m_detail = x.m_detail;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ServiceHeartbeat that will be copied.
     */
    eProsima_user_DllExport ServiceHeartbeat& operator =(
            ServiceHeartbeat&& x) noexcept
    {

        m_header_st = std::move(x.m_header_st);
        m_service_name = std::move(x.m_service_name);
        m_status = x.m_status;
        m_detail = std::move(x.m_detail);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ServiceHeartbeat object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ServiceHeartbeat& x) const
    {
        return (m_header_st == x.m_header_st &&
           m_service_name == x.m_service_name &&
           m_status == x.m_status &&
           m_detail == x.m_detail);
    }

    /*!
     * @brief Comparison operator.
     * @param x ServiceHeartbeat object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ServiceHeartbeat& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member header_st
     * @param _header_st New value to be copied in member header_st
     */
    eProsima_user_DllExport void header_st(
            const Header& _header_st)
    {
        m_header_st = _header_st;
    }

    /*!
     * @brief This function moves the value in member header_st
     * @param _header_st New value to be moved in member header_st
     */
    eProsima_user_DllExport void header_st(
            Header&& _header_st)
    {
        m_header_st = std::move(_header_st);
    }

    /*!
     * @brief This function returns a constant reference to member header_st
     * @return Constant reference to member header_st
     */
    eProsima_user_DllExport const Header& header_st() const
    {
        return m_header_st;
    }

    /*!
     * @brief This function returns a reference to member header_st
     * @return Reference to member header_st
     */
    eProsima_user_DllExport Header& header_st()
    {
        return m_header_st;
    }


    /*!
     * @brief This function copies the value in member service_name
     * @param _service_name New value to be copied in member service_name
     */
    eProsima_user_DllExport void service_name(
            const std::string& _service_name)
    {
        m_service_name = _service_name;
    }

    /*!
     * @brief This function moves the value in member service_name
     * @param _service_name New value to be moved in member service_name
     */
    eProsima_user_DllExport void service_name(
            std::string&& _service_name)
    {
        m_service_name = std::move(_service_name);
    }

    /*!
     * @brief This function returns a constant reference to member service_name
     * @return Constant reference to member service_name
     */
    eProsima_user_DllExport const std::string& service_name() const
    {
        return m_service_name;
    }

    /*!
     * @brief This function returns a reference to member service_name
     * @return Reference to member service_name
     */
    eProsima_user_DllExport std::string& service_name()
    {
        return m_service_name;
    }


    /*!
     * @brief This function sets a value in member status
     * @param _status New value for member status
     */
    eProsima_user_DllExport void status(
            HealthStatus _status)
    {
        m_status = _status;
    }

    /*!
     * @brief This function returns the value of member status
     * @return Value of member status
     */
    eProsima_user_DllExport HealthStatus status() const
    {
        return m_status;
    }

    /*!
     * @brief This function returns a reference to member status
     * @return Reference to member status
     */
    eProsima_user_DllExport HealthStatus& status()
    {
        return m_status;
    }


    /*!
     * @brief This function copies the value in member detail
     * @param _detail New value to be copied in member detail
     */
    eProsima_user_DllExport void detail(
            const std::string& _detail)
    {
        m_detail = _detail;
    }

    /*!
     * @brief This function moves the value in member detail
     * @param _detail New value to be moved in member detail
     */
    eProsima_user_DllExport void detail(
            std::string&& _detail)
    {
        m_detail = std::move(_detail);
    }

    /*!
     * @brief This function returns a constant reference to member detail
     * @return Constant reference to member detail
     */
    eProsima_user_DllExport const std::string& detail() const
    {
        return m_detail;
    }

    /*!
     * @brief This function returns a reference to member detail
     * @return Reference to member detail
     */
    eProsima_user_DllExport std::string& detail()
    {
        return m_detail;
    }



private:

    Header m_header_st;
    std::string m_service_name;
    HealthStatus m_status{HealthStatus::HEALTH_UNKNOWN};
    std::string m_detail;

};
/*!
 * @brief This class represents the enumeration PolicyMode defined by the user in the IDL file.
 * @ingroup common
 */
enum class PolicyMode : int32_t
{
    POLICY_UNKNOWN,
    POLICY_NOMINAL,
    POLICY_LOW_SOC,
    POLICY_EDGE_AUTONOMOUS,
    POLICY_DEGRADED_SERVER_DOWN,
    POLICY_DEGRADED_COMPLETE
};

} // namespace common

} // namespace safe_edge

#endif // _FAST_DDS_GENERATED_SAFE_EDGE_COMMON_COMMON_HPP_


