// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file edgeTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "edgeTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "edge.hpp"

#include "common.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace safe_edge {
namespace edge {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_VehicleEdgeSummary_type_identifier(
        TypeIdentifierPair& type_ids_VehicleEdgeSummary)
{

    ReturnCode_t return_code_VehicleEdgeSummary {eprosima::fastdds::dds::RETCODE_OK};
    return_code_VehicleEdgeSummary =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::edge::VehicleEdgeSummary", type_ids_VehicleEdgeSummary);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_VehicleEdgeSummary)
    {
        StructTypeFlag struct_flags_VehicleEdgeSummary = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_VehicleEdgeSummary = "safe_edge::edge::VehicleEdgeSummary";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_VehicleEdgeSummary;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_VehicleEdgeSummary;
        CompleteTypeDetail detail_VehicleEdgeSummary = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_VehicleEdgeSummary, ann_custom_VehicleEdgeSummary, type_name_VehicleEdgeSummary.to_string());
        CompleteStructHeader header_VehicleEdgeSummary;
        header_VehicleEdgeSummary = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_VehicleEdgeSummary);
        CompleteStructMemberSeq member_seq_VehicleEdgeSummary;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::common::Header", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
                ::safe_edge::common::register_Header_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_VehicleEdgeSummary.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_VehicleEdgeSummary);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_VehicleEdgeSummary, member_header);
        }
        {
            TypeIdentifierPair type_ids_soc_pct;
            ReturnCode_t return_code_soc_pct {eprosima::fastdds::dds::RETCODE_OK};
            return_code_soc_pct =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_soc_pct);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_soc_pct)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "soc_pct Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_soc_pct = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_soc_pct = 0x00000001;
            bool common_soc_pct_ec {false};
            CommonStructMember common_soc_pct {TypeObjectUtils::build_common_struct_member(member_id_soc_pct, member_flags_soc_pct, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_soc_pct, common_soc_pct_ec))};
            if (!common_soc_pct_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure soc_pct member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_soc_pct = "soc_pct";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_soc_pct;
            ann_custom_VehicleEdgeSummary.reset();
            CompleteMemberDetail detail_soc_pct = TypeObjectUtils::build_complete_member_detail(name_soc_pct, member_ann_builtin_soc_pct, ann_custom_VehicleEdgeSummary);
            CompleteStructMember member_soc_pct = TypeObjectUtils::build_complete_struct_member(common_soc_pct, detail_soc_pct);
            TypeObjectUtils::add_complete_struct_member(member_seq_VehicleEdgeSummary, member_soc_pct);
        }
        {
            TypeIdentifierPair type_ids_current_mode;
            ReturnCode_t return_code_current_mode {eprosima::fastdds::dds::RETCODE_OK};
            return_code_current_mode =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::common::PolicyMode", type_ids_current_mode);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_current_mode)
            {
                ::safe_edge::common::register_PolicyMode_type_identifier(type_ids_current_mode);
            }
            StructMemberFlag member_flags_current_mode = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_current_mode = 0x00000002;
            bool common_current_mode_ec {false};
            CommonStructMember common_current_mode {TypeObjectUtils::build_common_struct_member(member_id_current_mode, member_flags_current_mode, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_current_mode, common_current_mode_ec))};
            if (!common_current_mode_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure current_mode member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_current_mode = "current_mode";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_current_mode;
            ann_custom_VehicleEdgeSummary.reset();
            CompleteMemberDetail detail_current_mode = TypeObjectUtils::build_complete_member_detail(name_current_mode, member_ann_builtin_current_mode, ann_custom_VehicleEdgeSummary);
            CompleteStructMember member_current_mode = TypeObjectUtils::build_complete_struct_member(common_current_mode, detail_current_mode);
            TypeObjectUtils::add_complete_struct_member(member_seq_VehicleEdgeSummary, member_current_mode);
        }
        {
            TypeIdentifierPair type_ids_vehicle_health;
            ReturnCode_t return_code_vehicle_health {eprosima::fastdds::dds::RETCODE_OK};
            return_code_vehicle_health =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::common::HealthStatus", type_ids_vehicle_health);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_vehicle_health)
            {
                ::safe_edge::common::register_HealthStatus_type_identifier(type_ids_vehicle_health);
            }
            StructMemberFlag member_flags_vehicle_health = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_vehicle_health = 0x00000003;
            bool common_vehicle_health_ec {false};
            CommonStructMember common_vehicle_health {TypeObjectUtils::build_common_struct_member(member_id_vehicle_health, member_flags_vehicle_health, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_vehicle_health, common_vehicle_health_ec))};
            if (!common_vehicle_health_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure vehicle_health member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_vehicle_health = "vehicle_health";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_vehicle_health;
            ann_custom_VehicleEdgeSummary.reset();
            CompleteMemberDetail detail_vehicle_health = TypeObjectUtils::build_complete_member_detail(name_vehicle_health, member_ann_builtin_vehicle_health, ann_custom_VehicleEdgeSummary);
            CompleteStructMember member_vehicle_health = TypeObjectUtils::build_complete_struct_member(common_vehicle_health, detail_vehicle_health);
            TypeObjectUtils::add_complete_struct_member(member_seq_VehicleEdgeSummary, member_vehicle_health);
        }
        {
            TypeIdentifierPair type_ids_v2g_ready;
            ReturnCode_t return_code_v2g_ready {eprosima::fastdds::dds::RETCODE_OK};
            return_code_v2g_ready =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_v2g_ready);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_v2g_ready)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "v2g_ready Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_v2g_ready = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_v2g_ready = 0x00000004;
            bool common_v2g_ready_ec {false};
            CommonStructMember common_v2g_ready {TypeObjectUtils::build_common_struct_member(member_id_v2g_ready, member_flags_v2g_ready, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_v2g_ready, common_v2g_ready_ec))};
            if (!common_v2g_ready_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure v2g_ready member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_v2g_ready = "v2g_ready";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_v2g_ready;
            ann_custom_VehicleEdgeSummary.reset();
            CompleteMemberDetail detail_v2g_ready = TypeObjectUtils::build_complete_member_detail(name_v2g_ready, member_ann_builtin_v2g_ready, ann_custom_VehicleEdgeSummary);
            CompleteStructMember member_v2g_ready = TypeObjectUtils::build_complete_struct_member(common_v2g_ready, detail_v2g_ready);
            TypeObjectUtils::add_complete_struct_member(member_seq_VehicleEdgeSummary, member_v2g_ready);
        }
        CompleteStructType struct_type_VehicleEdgeSummary = TypeObjectUtils::build_complete_struct_type(struct_flags_VehicleEdgeSummary, header_VehicleEdgeSummary, member_seq_VehicleEdgeSummary);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_VehicleEdgeSummary, type_name_VehicleEdgeSummary.to_string(), type_ids_VehicleEdgeSummary))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::edge::VehicleEdgeSummary already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_EnergyAdvisory_type_identifier(
        TypeIdentifierPair& type_ids_EnergyAdvisory)
{

    ReturnCode_t return_code_EnergyAdvisory {eprosima::fastdds::dds::RETCODE_OK};
    return_code_EnergyAdvisory =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::edge::EnergyAdvisory", type_ids_EnergyAdvisory);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_EnergyAdvisory)
    {
        StructTypeFlag struct_flags_EnergyAdvisory = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_EnergyAdvisory = "safe_edge::edge::EnergyAdvisory";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_EnergyAdvisory;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_EnergyAdvisory;
        CompleteTypeDetail detail_EnergyAdvisory = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_EnergyAdvisory, ann_custom_EnergyAdvisory, type_name_EnergyAdvisory.to_string());
        CompleteStructHeader header_EnergyAdvisory;
        header_EnergyAdvisory = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_EnergyAdvisory);
        CompleteStructMemberSeq member_seq_EnergyAdvisory;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::common::Header", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
                ::safe_edge::common::register_Header_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_EnergyAdvisory.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_EnergyAdvisory);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_EnergyAdvisory, member_header);
        }
        {
            TypeIdentifierPair type_ids_suggested_mode;
            ReturnCode_t return_code_suggested_mode {eprosima::fastdds::dds::RETCODE_OK};
            return_code_suggested_mode =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::common::PolicyMode", type_ids_suggested_mode);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_suggested_mode)
            {
                ::safe_edge::common::register_PolicyMode_type_identifier(type_ids_suggested_mode);
            }
            StructMemberFlag member_flags_suggested_mode = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_suggested_mode = 0x00000001;
            bool common_suggested_mode_ec {false};
            CommonStructMember common_suggested_mode {TypeObjectUtils::build_common_struct_member(member_id_suggested_mode, member_flags_suggested_mode, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_suggested_mode, common_suggested_mode_ec))};
            if (!common_suggested_mode_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure suggested_mode member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_suggested_mode = "suggested_mode";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_suggested_mode;
            ann_custom_EnergyAdvisory.reset();
            CompleteMemberDetail detail_suggested_mode = TypeObjectUtils::build_complete_member_detail(name_suggested_mode, member_ann_builtin_suggested_mode, ann_custom_EnergyAdvisory);
            CompleteStructMember member_suggested_mode = TypeObjectUtils::build_complete_struct_member(common_suggested_mode, detail_suggested_mode);
            TypeObjectUtils::add_complete_struct_member(member_seq_EnergyAdvisory, member_suggested_mode);
        }
        {
            TypeIdentifierPair type_ids_advisory_reason;
            ReturnCode_t return_code_advisory_reason {eprosima::fastdds::dds::RETCODE_OK};
            return_code_advisory_reason =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_advisory_reason);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_advisory_reason)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_advisory_reason))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_advisory_reason = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_advisory_reason = 0x00000002;
            bool common_advisory_reason_ec {false};
            CommonStructMember common_advisory_reason {TypeObjectUtils::build_common_struct_member(member_id_advisory_reason, member_flags_advisory_reason, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_advisory_reason, common_advisory_reason_ec))};
            if (!common_advisory_reason_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure advisory_reason member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_advisory_reason = "advisory_reason";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_advisory_reason;
            ann_custom_EnergyAdvisory.reset();
            CompleteMemberDetail detail_advisory_reason = TypeObjectUtils::build_complete_member_detail(name_advisory_reason, member_ann_builtin_advisory_reason, ann_custom_EnergyAdvisory);
            CompleteStructMember member_advisory_reason = TypeObjectUtils::build_complete_struct_member(common_advisory_reason, detail_advisory_reason);
            TypeObjectUtils::add_complete_struct_member(member_seq_EnergyAdvisory, member_advisory_reason);
        }
        {
            TypeIdentifierPair type_ids_recommended_charger_id;
            ReturnCode_t return_code_recommended_charger_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_recommended_charger_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_recommended_charger_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_recommended_charger_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "recommended_charger_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_recommended_charger_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_recommended_charger_id = 0x00000003;
            bool common_recommended_charger_id_ec {false};
            CommonStructMember common_recommended_charger_id {TypeObjectUtils::build_common_struct_member(member_id_recommended_charger_id, member_flags_recommended_charger_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_recommended_charger_id, common_recommended_charger_id_ec))};
            if (!common_recommended_charger_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure recommended_charger_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_recommended_charger_id = "recommended_charger_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_recommended_charger_id;
            ann_custom_EnergyAdvisory.reset();
            CompleteMemberDetail detail_recommended_charger_id = TypeObjectUtils::build_complete_member_detail(name_recommended_charger_id, member_ann_builtin_recommended_charger_id, ann_custom_EnergyAdvisory);
            CompleteStructMember member_recommended_charger_id = TypeObjectUtils::build_complete_struct_member(common_recommended_charger_id, detail_recommended_charger_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_EnergyAdvisory, member_recommended_charger_id);
        }
        {
            TypeIdentifierPair type_ids_target_soc_pct;
            ReturnCode_t return_code_target_soc_pct {eprosima::fastdds::dds::RETCODE_OK};
            return_code_target_soc_pct =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_target_soc_pct);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_target_soc_pct)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "target_soc_pct Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_target_soc_pct = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_target_soc_pct = 0x00000004;
            bool common_target_soc_pct_ec {false};
            CommonStructMember common_target_soc_pct {TypeObjectUtils::build_common_struct_member(member_id_target_soc_pct, member_flags_target_soc_pct, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_target_soc_pct, common_target_soc_pct_ec))};
            if (!common_target_soc_pct_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure target_soc_pct member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_target_soc_pct = "target_soc_pct";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_target_soc_pct;
            ann_custom_EnergyAdvisory.reset();
            CompleteMemberDetail detail_target_soc_pct = TypeObjectUtils::build_complete_member_detail(name_target_soc_pct, member_ann_builtin_target_soc_pct, ann_custom_EnergyAdvisory);
            CompleteStructMember member_target_soc_pct = TypeObjectUtils::build_complete_struct_member(common_target_soc_pct, detail_target_soc_pct);
            TypeObjectUtils::add_complete_struct_member(member_seq_EnergyAdvisory, member_target_soc_pct);
        }
        CompleteStructType struct_type_EnergyAdvisory = TypeObjectUtils::build_complete_struct_type(struct_flags_EnergyAdvisory, header_EnergyAdvisory, member_seq_EnergyAdvisory);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_EnergyAdvisory, type_name_EnergyAdvisory.to_string(), type_ids_EnergyAdvisory))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::edge::EnergyAdvisory already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_EdgeGatewayStatus_type_identifier(
        TypeIdentifierPair& type_ids_EdgeGatewayStatus)
{

    ReturnCode_t return_code_EdgeGatewayStatus {eprosima::fastdds::dds::RETCODE_OK};
    return_code_EdgeGatewayStatus =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::edge::EdgeGatewayStatus", type_ids_EdgeGatewayStatus);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_EdgeGatewayStatus)
    {
        StructTypeFlag struct_flags_EdgeGatewayStatus = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_EdgeGatewayStatus = "safe_edge::edge::EdgeGatewayStatus";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_EdgeGatewayStatus;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_EdgeGatewayStatus;
        CompleteTypeDetail detail_EdgeGatewayStatus = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_EdgeGatewayStatus, ann_custom_EdgeGatewayStatus, type_name_EdgeGatewayStatus.to_string());
        CompleteStructHeader header_EdgeGatewayStatus;
        header_EdgeGatewayStatus = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_EdgeGatewayStatus);
        CompleteStructMemberSeq member_seq_EdgeGatewayStatus;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::common::Header", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
                ::safe_edge::common::register_Header_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_EdgeGatewayStatus.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_EdgeGatewayStatus);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_EdgeGatewayStatus, member_header);
        }
        {
            TypeIdentifierPair type_ids_status;
            ReturnCode_t return_code_status {eprosima::fastdds::dds::RETCODE_OK};
            return_code_status =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::common::HealthStatus", type_ids_status);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_status)
            {
                ::safe_edge::common::register_HealthStatus_type_identifier(type_ids_status);
            }
            StructMemberFlag member_flags_status = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_status = 0x00000001;
            bool common_status_ec {false};
            CommonStructMember common_status {TypeObjectUtils::build_common_struct_member(member_id_status, member_flags_status, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_status, common_status_ec))};
            if (!common_status_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure status member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_status = "status";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_status;
            ann_custom_EdgeGatewayStatus.reset();
            CompleteMemberDetail detail_status = TypeObjectUtils::build_complete_member_detail(name_status, member_ann_builtin_status, ann_custom_EdgeGatewayStatus);
            CompleteStructMember member_status = TypeObjectUtils::build_complete_struct_member(common_status, detail_status);
            TypeObjectUtils::add_complete_struct_member(member_seq_EdgeGatewayStatus, member_status);
        }
        {
            TypeIdentifierPair type_ids_last_server_sync_ms;
            ReturnCode_t return_code_last_server_sync_ms {eprosima::fastdds::dds::RETCODE_OK};
            return_code_last_server_sync_ms =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_last_server_sync_ms);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_last_server_sync_ms)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "last_server_sync_ms Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_last_server_sync_ms = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_last_server_sync_ms = 0x00000002;
            bool common_last_server_sync_ms_ec {false};
            CommonStructMember common_last_server_sync_ms {TypeObjectUtils::build_common_struct_member(member_id_last_server_sync_ms, member_flags_last_server_sync_ms, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_last_server_sync_ms, common_last_server_sync_ms_ec))};
            if (!common_last_server_sync_ms_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure last_server_sync_ms member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_last_server_sync_ms = "last_server_sync_ms";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_last_server_sync_ms;
            ann_custom_EdgeGatewayStatus.reset();
            CompleteMemberDetail detail_last_server_sync_ms = TypeObjectUtils::build_complete_member_detail(name_last_server_sync_ms, member_ann_builtin_last_server_sync_ms, ann_custom_EdgeGatewayStatus);
            CompleteStructMember member_last_server_sync_ms = TypeObjectUtils::build_complete_struct_member(common_last_server_sync_ms, detail_last_server_sync_ms);
            TypeObjectUtils::add_complete_struct_member(member_seq_EdgeGatewayStatus, member_last_server_sync_ms);
        }
        {
            TypeIdentifierPair type_ids_detail;
            ReturnCode_t return_code_detail {eprosima::fastdds::dds::RETCODE_OK};
            return_code_detail =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_detail);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_detail)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_detail))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_detail = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_detail = 0x00000003;
            bool common_detail_ec {false};
            CommonStructMember common_detail {TypeObjectUtils::build_common_struct_member(member_id_detail, member_flags_detail, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_detail, common_detail_ec))};
            if (!common_detail_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure detail member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_detail = "detail";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_detail;
            ann_custom_EdgeGatewayStatus.reset();
            CompleteMemberDetail detail_detail = TypeObjectUtils::build_complete_member_detail(name_detail, member_ann_builtin_detail, ann_custom_EdgeGatewayStatus);
            CompleteStructMember member_detail = TypeObjectUtils::build_complete_struct_member(common_detail, detail_detail);
            TypeObjectUtils::add_complete_struct_member(member_seq_EdgeGatewayStatus, member_detail);
        }
        CompleteStructType struct_type_EdgeGatewayStatus = TypeObjectUtils::build_complete_struct_type(struct_flags_EdgeGatewayStatus, header_EdgeGatewayStatus, member_seq_EdgeGatewayStatus);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_EdgeGatewayStatus, type_name_EdgeGatewayStatus.to_string(), type_ids_EdgeGatewayStatus))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::edge::EdgeGatewayStatus already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace edge

} // namespace safe_edge

