// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file pilot_serverTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "pilot_serverTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "pilot_server.hpp"

#include "common.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace safe_edge {
namespace pilot_server {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ChargerLocation_type_identifier(
        TypeIdentifierPair& type_ids_ChargerLocation)
{

    ReturnCode_t return_code_ChargerLocation {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ChargerLocation =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::ChargerLocation", type_ids_ChargerLocation);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargerLocation)
    {
        StructTypeFlag struct_flags_ChargerLocation = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_ChargerLocation = "safe_edge::pilot_server::ChargerLocation";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ChargerLocation;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ChargerLocation;
        CompleteTypeDetail detail_ChargerLocation = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ChargerLocation, ann_custom_ChargerLocation, type_name_ChargerLocation.to_string());
        CompleteStructHeader header_ChargerLocation;
        header_ChargerLocation = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ChargerLocation);
        CompleteStructMemberSeq member_seq_ChargerLocation;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_ChargerLocation.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_ChargerLocation);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargerLocation, member_id);
        }
        {
            TypeIdentifierPair type_ids_name;
            ReturnCode_t return_code_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_name)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_name = 0x00000001;
            bool common_name_ec {false};
            CommonStructMember common_name {TypeObjectUtils::build_common_struct_member(member_id_name, member_flags_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_name, common_name_ec))};
            if (!common_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_name = "name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_name;
            ann_custom_ChargerLocation.reset();
            CompleteMemberDetail detail_name = TypeObjectUtils::build_complete_member_detail(name_name, member_ann_builtin_name, ann_custom_ChargerLocation);
            CompleteStructMember member_name = TypeObjectUtils::build_complete_struct_member(common_name, detail_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargerLocation, member_name);
        }
        {
            TypeIdentifierPair type_ids_position;
            ReturnCode_t return_code_position {eprosima::fastdds::dds::RETCODE_OK};
            return_code_position =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::common::GeoPoint", type_ids_position);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_position)
            {
                ::safe_edge::common::register_GeoPoint_type_identifier(type_ids_position);
            }
            StructMemberFlag member_flags_position = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_position = 0x00000002;
            bool common_position_ec {false};
            CommonStructMember common_position {TypeObjectUtils::build_common_struct_member(member_id_position, member_flags_position, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position, common_position_ec))};
            if (!common_position_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure position member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_position = "position";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_position;
            ann_custom_ChargerLocation.reset();
            CompleteMemberDetail detail_position = TypeObjectUtils::build_complete_member_detail(name_position, member_ann_builtin_position, ann_custom_ChargerLocation);
            CompleteStructMember member_position = TypeObjectUtils::build_complete_struct_member(common_position, detail_position);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargerLocation, member_position);
        }
        CompleteStructType struct_type_ChargerLocation = TypeObjectUtils::build_complete_struct_type(struct_flags_ChargerLocation, header_ChargerLocation, member_seq_ChargerLocation);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ChargerLocation, type_name_ChargerLocation.to_string(), type_ids_ChargerLocation))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::pilot_server::ChargerLocation already registered in TypeObjectRegistry for a different type.");
        }
    }
}void register_ChargerLocationSeq_type_identifier(
        TypeIdentifierPair& type_ids_ChargerLocationSeq)
{
    ReturnCode_t return_code_ChargerLocationSeq {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ChargerLocationSeq =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::ChargerLocationSeq", type_ids_ChargerLocationSeq);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargerLocationSeq)
    {
        AliasTypeFlag alias_flags_ChargerLocationSeq = 0;
        QualifiedTypeName type_name_ChargerLocationSeq = "safe_edge::pilot_server::ChargerLocationSeq";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ChargerLocationSeq;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ChargerLocationSeq;
        CompleteTypeDetail detail_ChargerLocationSeq = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ChargerLocationSeq, ann_custom_ChargerLocationSeq, type_name_ChargerLocationSeq.to_string());
        CompleteAliasHeader header_ChargerLocationSeq = TypeObjectUtils::build_complete_alias_header(detail_ChargerLocationSeq);
        AliasMemberFlag related_flags_ChargerLocationSeq = 0;
        return_code_ChargerLocationSeq =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200", type_ids_ChargerLocationSeq);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargerLocationSeq)
        {
            return_code_ChargerLocationSeq =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::pilot_server::ChargerLocation", type_ids_ChargerLocationSeq);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargerLocationSeq)
            {
                ::safe_edge::pilot_server::register_ChargerLocation_type_identifier(type_ids_ChargerLocationSeq);
            }
            bool element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200_ec {false};
            TypeIdentifier* element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ChargerLocationSeq, element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200_ec))};
            if (!element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                return;
            }
            EquivalenceKind equiv_kind_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200 = EK_COMPLETE;
            if (TK_NONE == type_ids_ChargerLocationSeq.type_identifier2()._d())
            {
                equiv_kind_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200 = EK_BOTH;
            }
            CollectionElementFlag element_flags_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200 = 0;
            PlainCollectionHeader header_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200, element_flags_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200);
            {
                SBound bound = static_cast<SBound>(200);
                PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200, bound,
                            eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200));
                if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                        TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200", type_ids_ChargerLocationSeq))
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "anonymous_sequence_safe_edge_pilot_server_ChargerLocation_200 already registered in TypeObjectRegistry for a different type.");
                }
            }
        }
        bool common_ChargerLocationSeq_ec {false};
        CommonAliasBody common_ChargerLocationSeq {TypeObjectUtils::build_common_alias_body(related_flags_ChargerLocationSeq,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ChargerLocationSeq, common_ChargerLocationSeq_ec))};
        if (!common_ChargerLocationSeq_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "safe_edge::pilot_server::ChargerLocationSeq related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ChargerLocationSeq;
        ann_custom_ChargerLocationSeq.reset();
        CompleteAliasBody body_ChargerLocationSeq = TypeObjectUtils::build_complete_alias_body(common_ChargerLocationSeq,
                member_ann_builtin_ChargerLocationSeq, ann_custom_ChargerLocationSeq);
        CompleteAliasType alias_type_ChargerLocationSeq = TypeObjectUtils::build_complete_alias_type(alias_flags_ChargerLocationSeq,
                header_ChargerLocationSeq, body_ChargerLocationSeq);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_ChargerLocationSeq,
                    type_name_ChargerLocationSeq.to_string(), type_ids_ChargerLocationSeq))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "safe_edge::pilot_server::ChargerLocationSeq already registered in TypeObjectRegistry for a different type.");
        }
    }
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ChargerType_type_identifier(
        TypeIdentifierPair& type_ids_ChargerType)
{

    ReturnCode_t return_code_ChargerType {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ChargerType =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::ChargerType", type_ids_ChargerType);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargerType)
    {
        StructTypeFlag struct_flags_ChargerType = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_ChargerType = "safe_edge::pilot_server::ChargerType";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ChargerType;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ChargerType;
        CompleteTypeDetail detail_ChargerType = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ChargerType, ann_custom_ChargerType, type_name_ChargerType.to_string());
        CompleteStructHeader header_ChargerType;
        header_ChargerType = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ChargerType);
        CompleteStructMemberSeq member_seq_ChargerType;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_ChargerType.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_ChargerType);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargerType, member_id);
        }
        {
            TypeIdentifierPair type_ids_charger_type;
            ReturnCode_t return_code_charger_type {eprosima::fastdds::dds::RETCODE_OK};
            return_code_charger_type =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_charger_type);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_charger_type)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_charger_type))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_charger_type = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_charger_type = 0x00000001;
            bool common_charger_type_ec {false};
            CommonStructMember common_charger_type {TypeObjectUtils::build_common_struct_member(member_id_charger_type, member_flags_charger_type, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_charger_type, common_charger_type_ec))};
            if (!common_charger_type_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure charger_type member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_charger_type = "charger_type";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_charger_type;
            ann_custom_ChargerType.reset();
            CompleteMemberDetail detail_charger_type = TypeObjectUtils::build_complete_member_detail(name_charger_type, member_ann_builtin_charger_type, ann_custom_ChargerType);
            CompleteStructMember member_charger_type = TypeObjectUtils::build_complete_struct_member(common_charger_type, detail_charger_type);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargerType, member_charger_type);
        }
        CompleteStructType struct_type_ChargerType = TypeObjectUtils::build_complete_struct_type(struct_flags_ChargerType, header_ChargerType, member_seq_ChargerType);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ChargerType, type_name_ChargerType.to_string(), type_ids_ChargerType))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::pilot_server::ChargerType already registered in TypeObjectRegistry for a different type.");
        }
    }
}void register_ChargerTypeSeq_type_identifier(
        TypeIdentifierPair& type_ids_ChargerTypeSeq)
{
    ReturnCode_t return_code_ChargerTypeSeq {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ChargerTypeSeq =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::ChargerTypeSeq", type_ids_ChargerTypeSeq);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargerTypeSeq)
    {
        AliasTypeFlag alias_flags_ChargerTypeSeq = 0;
        QualifiedTypeName type_name_ChargerTypeSeq = "safe_edge::pilot_server::ChargerTypeSeq";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ChargerTypeSeq;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ChargerTypeSeq;
        CompleteTypeDetail detail_ChargerTypeSeq = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ChargerTypeSeq, ann_custom_ChargerTypeSeq, type_name_ChargerTypeSeq.to_string());
        CompleteAliasHeader header_ChargerTypeSeq = TypeObjectUtils::build_complete_alias_header(detail_ChargerTypeSeq);
        AliasMemberFlag related_flags_ChargerTypeSeq = 0;
        return_code_ChargerTypeSeq =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "anonymous_sequence_safe_edge_pilot_server_ChargerType_64", type_ids_ChargerTypeSeq);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargerTypeSeq)
        {
            return_code_ChargerTypeSeq =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::pilot_server::ChargerType", type_ids_ChargerTypeSeq);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargerTypeSeq)
            {
                ::safe_edge::pilot_server::register_ChargerType_type_identifier(type_ids_ChargerTypeSeq);
            }
            bool element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargerType_64_ec {false};
            TypeIdentifier* element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargerType_64 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ChargerTypeSeq, element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargerType_64_ec))};
            if (!element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargerType_64_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                return;
            }
            EquivalenceKind equiv_kind_anonymous_sequence_safe_edge_pilot_server_ChargerType_64 = EK_COMPLETE;
            if (TK_NONE == type_ids_ChargerTypeSeq.type_identifier2()._d())
            {
                equiv_kind_anonymous_sequence_safe_edge_pilot_server_ChargerType_64 = EK_BOTH;
            }
            CollectionElementFlag element_flags_anonymous_sequence_safe_edge_pilot_server_ChargerType_64 = 0;
            PlainCollectionHeader header_anonymous_sequence_safe_edge_pilot_server_ChargerType_64 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_safe_edge_pilot_server_ChargerType_64, element_flags_anonymous_sequence_safe_edge_pilot_server_ChargerType_64);
            {
                SBound bound = static_cast<SBound>(64);
                PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_safe_edge_pilot_server_ChargerType_64, bound,
                            eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargerType_64));
                if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                        TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_safe_edge_pilot_server_ChargerType_64", type_ids_ChargerTypeSeq))
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "anonymous_sequence_safe_edge_pilot_server_ChargerType_64 already registered in TypeObjectRegistry for a different type.");
                }
            }
        }
        bool common_ChargerTypeSeq_ec {false};
        CommonAliasBody common_ChargerTypeSeq {TypeObjectUtils::build_common_alias_body(related_flags_ChargerTypeSeq,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ChargerTypeSeq, common_ChargerTypeSeq_ec))};
        if (!common_ChargerTypeSeq_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "safe_edge::pilot_server::ChargerTypeSeq related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ChargerTypeSeq;
        ann_custom_ChargerTypeSeq.reset();
        CompleteAliasBody body_ChargerTypeSeq = TypeObjectUtils::build_complete_alias_body(common_ChargerTypeSeq,
                member_ann_builtin_ChargerTypeSeq, ann_custom_ChargerTypeSeq);
        CompleteAliasType alias_type_ChargerTypeSeq = TypeObjectUtils::build_complete_alias_type(alias_flags_ChargerTypeSeq,
                header_ChargerTypeSeq, body_ChargerTypeSeq);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_ChargerTypeSeq,
                    type_name_ChargerTypeSeq.to_string(), type_ids_ChargerTypeSeq))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "safe_edge::pilot_server::ChargerTypeSeq already registered in TypeObjectRegistry for a different type.");
        }
    }
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ChargingSession_type_identifier(
        TypeIdentifierPair& type_ids_ChargingSession)
{

    ReturnCode_t return_code_ChargingSession {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ChargingSession =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::ChargingSession", type_ids_ChargingSession);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargingSession)
    {
        StructTypeFlag struct_flags_ChargingSession = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_ChargingSession = "safe_edge::pilot_server::ChargingSession";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ChargingSession;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ChargingSession;
        CompleteTypeDetail detail_ChargingSession = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ChargingSession, ann_custom_ChargingSession, type_name_ChargingSession.to_string());
        CompleteStructHeader header_ChargingSession;
        header_ChargingSession = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ChargingSession);
        CompleteStructMemberSeq member_seq_ChargingSession;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_ChargingSession.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_ChargingSession);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargingSession, member_id);
        }
        {
            TypeIdentifierPair type_ids_station_id;
            ReturnCode_t return_code_station_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_station_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_station_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_station_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "station_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_station_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_station_id = 0x00000001;
            bool common_station_id_ec {false};
            CommonStructMember common_station_id {TypeObjectUtils::build_common_struct_member(member_id_station_id, member_flags_station_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_station_id, common_station_id_ec))};
            if (!common_station_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure station_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_station_id = "station_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_station_id;
            ann_custom_ChargingSession.reset();
            CompleteMemberDetail detail_station_id = TypeObjectUtils::build_complete_member_detail(name_station_id, member_ann_builtin_station_id, ann_custom_ChargingSession);
            CompleteStructMember member_station_id = TypeObjectUtils::build_complete_struct_member(common_station_id, detail_station_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargingSession, member_station_id);
        }
        {
            TypeIdentifierPair type_ids_charger_type_id;
            ReturnCode_t return_code_charger_type_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_charger_type_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_charger_type_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_charger_type_id)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_charger_type_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_charger_type_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_charger_type_id = 0x00000002;
            bool common_charger_type_id_ec {false};
            CommonStructMember common_charger_type_id {TypeObjectUtils::build_common_struct_member(member_id_charger_type_id, member_flags_charger_type_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_charger_type_id, common_charger_type_id_ec))};
            if (!common_charger_type_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure charger_type_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_charger_type_id = "charger_type_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_charger_type_id;
            ann_custom_ChargingSession.reset();
            CompleteMemberDetail detail_charger_type_id = TypeObjectUtils::build_complete_member_detail(name_charger_type_id, member_ann_builtin_charger_type_id, ann_custom_ChargingSession);
            CompleteStructMember member_charger_type_id = TypeObjectUtils::build_complete_struct_member(common_charger_type_id, detail_charger_type_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargingSession, member_charger_type_id);
        }
        {
            TypeIdentifierPair type_ids_consume_wh;
            ReturnCode_t return_code_consume_wh {eprosima::fastdds::dds::RETCODE_OK};
            return_code_consume_wh =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_consume_wh);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_consume_wh)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "consume_wh Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_consume_wh = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_consume_wh = 0x00000003;
            bool common_consume_wh_ec {false};
            CommonStructMember common_consume_wh {TypeObjectUtils::build_common_struct_member(member_id_consume_wh, member_flags_consume_wh, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_consume_wh, common_consume_wh_ec))};
            if (!common_consume_wh_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure consume_wh member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_consume_wh = "consume_wh";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_consume_wh;
            ann_custom_ChargingSession.reset();
            CompleteMemberDetail detail_consume_wh = TypeObjectUtils::build_complete_member_detail(name_consume_wh, member_ann_builtin_consume_wh, ann_custom_ChargingSession);
            CompleteStructMember member_consume_wh = TypeObjectUtils::build_complete_struct_member(common_consume_wh, detail_consume_wh);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargingSession, member_consume_wh);
        }
        {
            TypeIdentifierPair type_ids_duration_min;
            ReturnCode_t return_code_duration_min {eprosima::fastdds::dds::RETCODE_OK};
            return_code_duration_min =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_duration_min);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_duration_min)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "duration_min Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_duration_min = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_duration_min = 0x00000004;
            bool common_duration_min_ec {false};
            CommonStructMember common_duration_min {TypeObjectUtils::build_common_struct_member(member_id_duration_min, member_flags_duration_min, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_duration_min, common_duration_min_ec))};
            if (!common_duration_min_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure duration_min member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_duration_min = "duration_min";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_duration_min;
            ann_custom_ChargingSession.reset();
            CompleteMemberDetail detail_duration_min = TypeObjectUtils::build_complete_member_detail(name_duration_min, member_ann_builtin_duration_min, ann_custom_ChargingSession);
            CompleteStructMember member_duration_min = TypeObjectUtils::build_complete_struct_member(common_duration_min, detail_duration_min);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargingSession, member_duration_min);
        }
        {
            TypeIdentifierPair type_ids_date_iso8601;
            ReturnCode_t return_code_date_iso8601 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_date_iso8601 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_date_iso8601);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_date_iso8601)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_date_iso8601))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_date_iso8601 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_date_iso8601 = 0x00000005;
            bool common_date_iso8601_ec {false};
            CommonStructMember common_date_iso8601 {TypeObjectUtils::build_common_struct_member(member_id_date_iso8601, member_flags_date_iso8601, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_date_iso8601, common_date_iso8601_ec))};
            if (!common_date_iso8601_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure date_iso8601 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_date_iso8601 = "date_iso8601";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_date_iso8601;
            ann_custom_ChargingSession.reset();
            CompleteMemberDetail detail_date_iso8601 = TypeObjectUtils::build_complete_member_detail(name_date_iso8601, member_ann_builtin_date_iso8601, ann_custom_ChargingSession);
            CompleteStructMember member_date_iso8601 = TypeObjectUtils::build_complete_struct_member(common_date_iso8601, detail_date_iso8601);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargingSession, member_date_iso8601);
        }
        {
            TypeIdentifierPair type_ids_ingested_at_iso8601;
            ReturnCode_t return_code_ingested_at_iso8601 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ingested_at_iso8601 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_ingested_at_iso8601);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ingested_at_iso8601)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_ingested_at_iso8601))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_ingested_at_iso8601 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ingested_at_iso8601 = 0x00000006;
            bool common_ingested_at_iso8601_ec {false};
            CommonStructMember common_ingested_at_iso8601 {TypeObjectUtils::build_common_struct_member(member_id_ingested_at_iso8601, member_flags_ingested_at_iso8601, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ingested_at_iso8601, common_ingested_at_iso8601_ec))};
            if (!common_ingested_at_iso8601_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ingested_at_iso8601 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ingested_at_iso8601 = "ingested_at_iso8601";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ingested_at_iso8601;
            ann_custom_ChargingSession.reset();
            CompleteMemberDetail detail_ingested_at_iso8601 = TypeObjectUtils::build_complete_member_detail(name_ingested_at_iso8601, member_ann_builtin_ingested_at_iso8601, ann_custom_ChargingSession);
            CompleteStructMember member_ingested_at_iso8601 = TypeObjectUtils::build_complete_struct_member(common_ingested_at_iso8601, detail_ingested_at_iso8601);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChargingSession, member_ingested_at_iso8601);
        }
        CompleteStructType struct_type_ChargingSession = TypeObjectUtils::build_complete_struct_type(struct_flags_ChargingSession, header_ChargingSession, member_seq_ChargingSession);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ChargingSession, type_name_ChargingSession.to_string(), type_ids_ChargingSession))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::pilot_server::ChargingSession already registered in TypeObjectRegistry for a different type.");
        }
    }
}void register_ChargingSessionSeq_type_identifier(
        TypeIdentifierPair& type_ids_ChargingSessionSeq)
{
    ReturnCode_t return_code_ChargingSessionSeq {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ChargingSessionSeq =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::ChargingSessionSeq", type_ids_ChargingSessionSeq);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargingSessionSeq)
    {
        AliasTypeFlag alias_flags_ChargingSessionSeq = 0;
        QualifiedTypeName type_name_ChargingSessionSeq = "safe_edge::pilot_server::ChargingSessionSeq";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ChargingSessionSeq;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ChargingSessionSeq;
        CompleteTypeDetail detail_ChargingSessionSeq = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ChargingSessionSeq, ann_custom_ChargingSessionSeq, type_name_ChargingSessionSeq.to_string());
        CompleteAliasHeader header_ChargingSessionSeq = TypeObjectUtils::build_complete_alias_header(detail_ChargingSessionSeq);
        AliasMemberFlag related_flags_ChargingSessionSeq = 0;
        return_code_ChargingSessionSeq =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000", type_ids_ChargingSessionSeq);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargingSessionSeq)
        {
            return_code_ChargingSessionSeq =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::pilot_server::ChargingSession", type_ids_ChargingSessionSeq);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChargingSessionSeq)
            {
                ::safe_edge::pilot_server::register_ChargingSession_type_identifier(type_ids_ChargingSessionSeq);
            }
            bool element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000_ec {false};
            TypeIdentifier* element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ChargingSessionSeq, element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000_ec))};
            if (!element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                return;
            }
            EquivalenceKind equiv_kind_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000 = EK_COMPLETE;
            if (TK_NONE == type_ids_ChargingSessionSeq.type_identifier2()._d())
            {
                equiv_kind_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000 = EK_BOTH;
            }
            CollectionElementFlag element_flags_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000 = 0;
            PlainCollectionHeader header_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000, element_flags_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000);
            {
                LBound bound = 1000;
                PlainSequenceLElemDefn seq_ldefn = TypeObjectUtils::build_plain_sequence_l_elem_defn(header_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000, bound,
                            eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000));
                if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                        TypeObjectUtils::build_and_register_l_sequence_type_identifier(seq_ldefn, "anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000", type_ids_ChargingSessionSeq))
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "anonymous_sequence_safe_edge_pilot_server_ChargingSession_1000 already registered in TypeObjectRegistry for a different type.");
                }
            }
        }
        bool common_ChargingSessionSeq_ec {false};
        CommonAliasBody common_ChargingSessionSeq {TypeObjectUtils::build_common_alias_body(related_flags_ChargingSessionSeq,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ChargingSessionSeq, common_ChargingSessionSeq_ec))};
        if (!common_ChargingSessionSeq_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "safe_edge::pilot_server::ChargingSessionSeq related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ChargingSessionSeq;
        ann_custom_ChargingSessionSeq.reset();
        CompleteAliasBody body_ChargingSessionSeq = TypeObjectUtils::build_complete_alias_body(common_ChargingSessionSeq,
                member_ann_builtin_ChargingSessionSeq, ann_custom_ChargingSessionSeq);
        CompleteAliasType alias_type_ChargingSessionSeq = TypeObjectUtils::build_complete_alias_type(alias_flags_ChargingSessionSeq,
                header_ChargingSessionSeq, body_ChargingSessionSeq);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_ChargingSessionSeq,
                    type_name_ChargingSessionSeq.to_string(), type_ids_ChargingSessionSeq))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "safe_edge::pilot_server::ChargingSessionSeq already registered in TypeObjectRegistry for a different type.");
        }
    }
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_TransitHealth_type_identifier(
        TypeIdentifierPair& type_ids_TransitHealth)
{

    ReturnCode_t return_code_TransitHealth {eprosima::fastdds::dds::RETCODE_OK};
    return_code_TransitHealth =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::TransitHealth", type_ids_TransitHealth);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_TransitHealth)
    {
        StructTypeFlag struct_flags_TransitHealth = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_TransitHealth = "safe_edge::pilot_server::TransitHealth";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_TransitHealth;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_TransitHealth;
        CompleteTypeDetail detail_TransitHealth = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_TransitHealth, ann_custom_TransitHealth, type_name_TransitHealth.to_string());
        CompleteStructHeader header_TransitHealth;
        header_TransitHealth = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_TransitHealth);
        CompleteStructMemberSeq member_seq_TransitHealth;
        {
            TypeIdentifierPair type_ids_status;
            ReturnCode_t return_code_status {eprosima::fastdds::dds::RETCODE_OK};
            return_code_status =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_status);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_status)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_status))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_status = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_status = 0x00000000;
            bool common_status_ec {false};
            CommonStructMember common_status {TypeObjectUtils::build_common_struct_member(member_id_status, member_flags_status, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_status, common_status_ec))};
            if (!common_status_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure status member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_status = "status";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_status;
            ann_custom_TransitHealth.reset();
            CompleteMemberDetail detail_status = TypeObjectUtils::build_complete_member_detail(name_status, member_ann_builtin_status, ann_custom_TransitHealth);
            CompleteStructMember member_status = TypeObjectUtils::build_complete_struct_member(common_status, detail_status);
            TypeObjectUtils::add_complete_struct_member(member_seq_TransitHealth, member_status);
        }
        {
            TypeIdentifierPair type_ids_last_fetch_ts;
            ReturnCode_t return_code_last_fetch_ts {eprosima::fastdds::dds::RETCODE_OK};
            return_code_last_fetch_ts =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_last_fetch_ts);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_last_fetch_ts)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "last_fetch_ts Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_last_fetch_ts = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_last_fetch_ts = 0x00000001;
            bool common_last_fetch_ts_ec {false};
            CommonStructMember common_last_fetch_ts {TypeObjectUtils::build_common_struct_member(member_id_last_fetch_ts, member_flags_last_fetch_ts, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_last_fetch_ts, common_last_fetch_ts_ec))};
            if (!common_last_fetch_ts_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure last_fetch_ts member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_last_fetch_ts = "last_fetch_ts";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_last_fetch_ts;
            ann_custom_TransitHealth.reset();
            CompleteMemberDetail detail_last_fetch_ts = TypeObjectUtils::build_complete_member_detail(name_last_fetch_ts, member_ann_builtin_last_fetch_ts, ann_custom_TransitHealth);
            CompleteStructMember member_last_fetch_ts = TypeObjectUtils::build_complete_struct_member(common_last_fetch_ts, detail_last_fetch_ts);
            TypeObjectUtils::add_complete_struct_member(member_seq_TransitHealth, member_last_fetch_ts);
        }
        CompleteStructType struct_type_TransitHealth = TypeObjectUtils::build_complete_struct_type(struct_flags_TransitHealth, header_TransitHealth, member_seq_TransitHealth);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_TransitHealth, type_name_TransitHealth.to_string(), type_ids_TransitHealth))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::pilot_server::TransitHealth already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_RouteMetric_type_identifier(
        TypeIdentifierPair& type_ids_RouteMetric)
{

    ReturnCode_t return_code_RouteMetric {eprosima::fastdds::dds::RETCODE_OK};
    return_code_RouteMetric =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::RouteMetric", type_ids_RouteMetric);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_RouteMetric)
    {
        StructTypeFlag struct_flags_RouteMetric = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_RouteMetric = "safe_edge::pilot_server::RouteMetric";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_RouteMetric;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_RouteMetric;
        CompleteTypeDetail detail_RouteMetric = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_RouteMetric, ann_custom_RouteMetric, type_name_RouteMetric.to_string());
        CompleteStructHeader header_RouteMetric;
        header_RouteMetric = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_RouteMetric);
        CompleteStructMemberSeq member_seq_RouteMetric;
        {
            TypeIdentifierPair type_ids_route_id;
            ReturnCode_t return_code_route_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_route_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_route_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_route_id)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_route_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_route_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_route_id = 0x00000000;
            bool common_route_id_ec {false};
            CommonStructMember common_route_id {TypeObjectUtils::build_common_struct_member(member_id_route_id, member_flags_route_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_route_id, common_route_id_ec))};
            if (!common_route_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure route_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_route_id = "route_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_route_id;
            ann_custom_RouteMetric.reset();
            CompleteMemberDetail detail_route_id = TypeObjectUtils::build_complete_member_detail(name_route_id, member_ann_builtin_route_id, ann_custom_RouteMetric);
            CompleteStructMember member_route_id = TypeObjectUtils::build_complete_struct_member(common_route_id, detail_route_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_RouteMetric, member_route_id);
        }
        {
            TypeIdentifierPair type_ids_updates_count;
            ReturnCode_t return_code_updates_count {eprosima::fastdds::dds::RETCODE_OK};
            return_code_updates_count =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_updates_count);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_updates_count)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "updates_count Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_updates_count = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_updates_count = 0x00000001;
            bool common_updates_count_ec {false};
            CommonStructMember common_updates_count {TypeObjectUtils::build_common_struct_member(member_id_updates_count, member_flags_updates_count, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_updates_count, common_updates_count_ec))};
            if (!common_updates_count_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure updates_count member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_updates_count = "updates_count";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_updates_count;
            ann_custom_RouteMetric.reset();
            CompleteMemberDetail detail_updates_count = TypeObjectUtils::build_complete_member_detail(name_updates_count, member_ann_builtin_updates_count, ann_custom_RouteMetric);
            CompleteStructMember member_updates_count = TypeObjectUtils::build_complete_struct_member(common_updates_count, detail_updates_count);
            TypeObjectUtils::add_complete_struct_member(member_seq_RouteMetric, member_updates_count);
        }
        CompleteStructType struct_type_RouteMetric = TypeObjectUtils::build_complete_struct_type(struct_flags_RouteMetric, header_RouteMetric, member_seq_RouteMetric);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_RouteMetric, type_name_RouteMetric.to_string(), type_ids_RouteMetric))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::pilot_server::RouteMetric already registered in TypeObjectRegistry for a different type.");
        }
    }
}void register_RouteMetricSeq_type_identifier(
        TypeIdentifierPair& type_ids_RouteMetricSeq)
{
    ReturnCode_t return_code_RouteMetricSeq {eprosima::fastdds::dds::RETCODE_OK};
    return_code_RouteMetricSeq =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::RouteMetricSeq", type_ids_RouteMetricSeq);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_RouteMetricSeq)
    {
        AliasTypeFlag alias_flags_RouteMetricSeq = 0;
        QualifiedTypeName type_name_RouteMetricSeq = "safe_edge::pilot_server::RouteMetricSeq";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_RouteMetricSeq;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_RouteMetricSeq;
        CompleteTypeDetail detail_RouteMetricSeq = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_RouteMetricSeq, ann_custom_RouteMetricSeq, type_name_RouteMetricSeq.to_string());
        CompleteAliasHeader header_RouteMetricSeq = TypeObjectUtils::build_complete_alias_header(detail_RouteMetricSeq);
        AliasMemberFlag related_flags_RouteMetricSeq = 0;
        return_code_RouteMetricSeq =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "anonymous_sequence_safe_edge_pilot_server_RouteMetric_512", type_ids_RouteMetricSeq);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_RouteMetricSeq)
        {
            return_code_RouteMetricSeq =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::pilot_server::RouteMetric", type_ids_RouteMetricSeq);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_RouteMetricSeq)
            {
                ::safe_edge::pilot_server::register_RouteMetric_type_identifier(type_ids_RouteMetricSeq);
            }
            bool element_identifier_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512_ec {false};
            TypeIdentifier* element_identifier_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_RouteMetricSeq, element_identifier_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512_ec))};
            if (!element_identifier_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                return;
            }
            EquivalenceKind equiv_kind_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512 = EK_COMPLETE;
            if (TK_NONE == type_ids_RouteMetricSeq.type_identifier2()._d())
            {
                equiv_kind_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512 = EK_BOTH;
            }
            CollectionElementFlag element_flags_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512 = 0;
            PlainCollectionHeader header_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512, element_flags_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512);
            {
                LBound bound = 512;
                PlainSequenceLElemDefn seq_ldefn = TypeObjectUtils::build_plain_sequence_l_elem_defn(header_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512, bound,
                            eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_safe_edge_pilot_server_RouteMetric_512));
                if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                        TypeObjectUtils::build_and_register_l_sequence_type_identifier(seq_ldefn, "anonymous_sequence_safe_edge_pilot_server_RouteMetric_512", type_ids_RouteMetricSeq))
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "anonymous_sequence_safe_edge_pilot_server_RouteMetric_512 already registered in TypeObjectRegistry for a different type.");
                }
            }
        }
        bool common_RouteMetricSeq_ec {false};
        CommonAliasBody common_RouteMetricSeq {TypeObjectUtils::build_common_alias_body(related_flags_RouteMetricSeq,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_RouteMetricSeq, common_RouteMetricSeq_ec))};
        if (!common_RouteMetricSeq_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "safe_edge::pilot_server::RouteMetricSeq related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_RouteMetricSeq;
        ann_custom_RouteMetricSeq.reset();
        CompleteAliasBody body_RouteMetricSeq = TypeObjectUtils::build_complete_alias_body(common_RouteMetricSeq,
                member_ann_builtin_RouteMetricSeq, ann_custom_RouteMetricSeq);
        CompleteAliasType alias_type_RouteMetricSeq = TypeObjectUtils::build_complete_alias_type(alias_flags_RouteMetricSeq,
                header_RouteMetricSeq, body_RouteMetricSeq);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_RouteMetricSeq,
                    type_name_RouteMetricSeq.to_string(), type_ids_RouteMetricSeq))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "safe_edge::pilot_server::RouteMetricSeq already registered in TypeObjectRegistry for a different type.");
        }
    }
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_TransitMetrics_type_identifier(
        TypeIdentifierPair& type_ids_TransitMetrics)
{

    ReturnCode_t return_code_TransitMetrics {eprosima::fastdds::dds::RETCODE_OK};
    return_code_TransitMetrics =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::TransitMetrics", type_ids_TransitMetrics);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_TransitMetrics)
    {
        StructTypeFlag struct_flags_TransitMetrics = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_TransitMetrics = "safe_edge::pilot_server::TransitMetrics";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_TransitMetrics;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_TransitMetrics;
        CompleteTypeDetail detail_TransitMetrics = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_TransitMetrics, ann_custom_TransitMetrics, type_name_TransitMetrics.to_string());
        CompleteStructHeader header_TransitMetrics;
        header_TransitMetrics = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_TransitMetrics);
        CompleteStructMemberSeq member_seq_TransitMetrics;
        {
            TypeIdentifierPair type_ids_by_route;
            ReturnCode_t return_code_by_route {eprosima::fastdds::dds::RETCODE_OK};
            return_code_by_route =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::pilot_server::RouteMetricSeq", type_ids_by_route);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_by_route)
            {
                ::safe_edge::pilot_server::register_RouteMetricSeq_type_identifier(type_ids_by_route);
            }
            StructMemberFlag member_flags_by_route = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_by_route = 0x00000000;
            bool common_by_route_ec {false};
            CommonStructMember common_by_route {TypeObjectUtils::build_common_struct_member(member_id_by_route, member_flags_by_route, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_by_route, common_by_route_ec))};
            if (!common_by_route_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure by_route member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_by_route = "by_route";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_by_route;
            ann_custom_TransitMetrics.reset();
            CompleteMemberDetail detail_by_route = TypeObjectUtils::build_complete_member_detail(name_by_route, member_ann_builtin_by_route, ann_custom_TransitMetrics);
            CompleteStructMember member_by_route = TypeObjectUtils::build_complete_struct_member(common_by_route, detail_by_route);
            TypeObjectUtils::add_complete_struct_member(member_seq_TransitMetrics, member_by_route);
        }
        {
            TypeIdentifierPair type_ids_vehicles_seen;
            ReturnCode_t return_code_vehicles_seen {eprosima::fastdds::dds::RETCODE_OK};
            return_code_vehicles_seen =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_vehicles_seen);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_vehicles_seen)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "vehicles_seen Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_vehicles_seen = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_vehicles_seen = 0x00000001;
            bool common_vehicles_seen_ec {false};
            CommonStructMember common_vehicles_seen {TypeObjectUtils::build_common_struct_member(member_id_vehicles_seen, member_flags_vehicles_seen, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_vehicles_seen, common_vehicles_seen_ec))};
            if (!common_vehicles_seen_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure vehicles_seen member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_vehicles_seen = "vehicles_seen";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_vehicles_seen;
            ann_custom_TransitMetrics.reset();
            CompleteMemberDetail detail_vehicles_seen = TypeObjectUtils::build_complete_member_detail(name_vehicles_seen, member_ann_builtin_vehicles_seen, ann_custom_TransitMetrics);
            CompleteStructMember member_vehicles_seen = TypeObjectUtils::build_complete_struct_member(common_vehicles_seen, detail_vehicles_seen);
            TypeObjectUtils::add_complete_struct_member(member_seq_TransitMetrics, member_vehicles_seen);
        }
        CompleteStructType struct_type_TransitMetrics = TypeObjectUtils::build_complete_struct_type(struct_flags_TransitMetrics, header_TransitMetrics, member_seq_TransitMetrics);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_TransitMetrics, type_name_TransitMetrics.to_string(), type_ids_TransitMetrics))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::pilot_server::TransitMetrics already registered in TypeObjectRegistry for a different type.");
        }
    }
}void register_RequestedDataType_type_identifier(
        TypeIdentifierPair& type_ids_RequestedDataType)
{
    ReturnCode_t return_code_RequestedDataType {eprosima::fastdds::dds::RETCODE_OK};
    return_code_RequestedDataType =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::RequestedDataType", type_ids_RequestedDataType);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_RequestedDataType)
    {
        EnumTypeFlag enum_flags_RequestedDataType = 0;
        BitBound bit_bound_RequestedDataType = 32;
        CommonEnumeratedHeader common_RequestedDataType = TypeObjectUtils::build_common_enumerated_header(bit_bound_RequestedDataType);
        QualifiedTypeName type_name_RequestedDataType = "safe_edge::pilot_server::RequestedDataType";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_RequestedDataType;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_RequestedDataType;
        CompleteTypeDetail detail_RequestedDataType = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_RequestedDataType, ann_custom_RequestedDataType, type_name_RequestedDataType.to_string());
        CompleteEnumeratedHeader header_RequestedDataType = TypeObjectUtils::build_complete_enumerated_header(common_RequestedDataType, detail_RequestedDataType);
        CompleteEnumeratedLiteralSeq literal_seq_RequestedDataType;
        {
            EnumeratedLiteralFlag flags_CHARGER_LOCATION = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_CHARGER_LOCATION = TypeObjectUtils::build_common_enumerated_literal(0, flags_CHARGER_LOCATION);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_CHARGER_LOCATION;
            ann_custom_RequestedDataType.reset();
            MemberName name_CHARGER_LOCATION = "CHARGER_LOCATION";
            CompleteMemberDetail detail_CHARGER_LOCATION = TypeObjectUtils::build_complete_member_detail(name_CHARGER_LOCATION, member_ann_builtin_CHARGER_LOCATION, ann_custom_RequestedDataType);
            CompleteEnumeratedLiteral literal_CHARGER_LOCATION = TypeObjectUtils::build_complete_enumerated_literal(common_CHARGER_LOCATION, detail_CHARGER_LOCATION);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_RequestedDataType, literal_CHARGER_LOCATION);
        }
        {
            EnumeratedLiteralFlag flags_CHARGER_TYPE = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_CHARGER_TYPE = TypeObjectUtils::build_common_enumerated_literal(1, flags_CHARGER_TYPE);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_CHARGER_TYPE;
            ann_custom_RequestedDataType.reset();
            MemberName name_CHARGER_TYPE = "CHARGER_TYPE";
            CompleteMemberDetail detail_CHARGER_TYPE = TypeObjectUtils::build_complete_member_detail(name_CHARGER_TYPE, member_ann_builtin_CHARGER_TYPE, ann_custom_RequestedDataType);
            CompleteEnumeratedLiteral literal_CHARGER_TYPE = TypeObjectUtils::build_complete_enumerated_literal(common_CHARGER_TYPE, detail_CHARGER_TYPE);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_RequestedDataType, literal_CHARGER_TYPE);
        }
        {
            EnumeratedLiteralFlag flags_CHARGING_SESSION = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_CHARGING_SESSION = TypeObjectUtils::build_common_enumerated_literal(2, flags_CHARGING_SESSION);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_CHARGING_SESSION;
            ann_custom_RequestedDataType.reset();
            MemberName name_CHARGING_SESSION = "CHARGING_SESSION";
            CompleteMemberDetail detail_CHARGING_SESSION = TypeObjectUtils::build_complete_member_detail(name_CHARGING_SESSION, member_ann_builtin_CHARGING_SESSION, ann_custom_RequestedDataType);
            CompleteEnumeratedLiteral literal_CHARGING_SESSION = TypeObjectUtils::build_complete_enumerated_literal(common_CHARGING_SESSION, detail_CHARGING_SESSION);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_RequestedDataType, literal_CHARGING_SESSION);
        }
        {
            EnumeratedLiteralFlag flags_TRANSIT_HEALTH = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_TRANSIT_HEALTH = TypeObjectUtils::build_common_enumerated_literal(3, flags_TRANSIT_HEALTH);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_TRANSIT_HEALTH;
            ann_custom_RequestedDataType.reset();
            MemberName name_TRANSIT_HEALTH = "TRANSIT_HEALTH";
            CompleteMemberDetail detail_TRANSIT_HEALTH = TypeObjectUtils::build_complete_member_detail(name_TRANSIT_HEALTH, member_ann_builtin_TRANSIT_HEALTH, ann_custom_RequestedDataType);
            CompleteEnumeratedLiteral literal_TRANSIT_HEALTH = TypeObjectUtils::build_complete_enumerated_literal(common_TRANSIT_HEALTH, detail_TRANSIT_HEALTH);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_RequestedDataType, literal_TRANSIT_HEALTH);
        }
        {
            EnumeratedLiteralFlag flags_TRANSIT_METRICS = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_TRANSIT_METRICS = TypeObjectUtils::build_common_enumerated_literal(4, flags_TRANSIT_METRICS);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_TRANSIT_METRICS;
            ann_custom_RequestedDataType.reset();
            MemberName name_TRANSIT_METRICS = "TRANSIT_METRICS";
            CompleteMemberDetail detail_TRANSIT_METRICS = TypeObjectUtils::build_complete_member_detail(name_TRANSIT_METRICS, member_ann_builtin_TRANSIT_METRICS, ann_custom_RequestedDataType);
            CompleteEnumeratedLiteral literal_TRANSIT_METRICS = TypeObjectUtils::build_complete_enumerated_literal(common_TRANSIT_METRICS, detail_TRANSIT_METRICS);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_RequestedDataType, literal_TRANSIT_METRICS);
        }
        CompleteEnumeratedType enumerated_type_RequestedDataType = TypeObjectUtils::build_complete_enumerated_type(enum_flags_RequestedDataType, header_RequestedDataType,
                literal_seq_RequestedDataType);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_enumerated_type_object(enumerated_type_RequestedDataType, type_name_RequestedDataType.to_string(), type_ids_RequestedDataType))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "safe_edge::pilot_server::RequestedDataType already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ServerQuery_type_identifier(
        TypeIdentifierPair& type_ids_ServerQuery)
{

    ReturnCode_t return_code_ServerQuery {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ServerQuery =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "safe_edge::pilot_server::ServerQuery", type_ids_ServerQuery);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ServerQuery)
    {
        StructTypeFlag struct_flags_ServerQuery = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_ServerQuery = "safe_edge::pilot_server::ServerQuery";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ServerQuery;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ServerQuery;
        CompleteTypeDetail detail_ServerQuery = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ServerQuery, ann_custom_ServerQuery, type_name_ServerQuery.to_string());
        CompleteStructHeader header_ServerQuery;
        header_ServerQuery = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ServerQuery);
        CompleteStructMemberSeq member_seq_ServerQuery;
        {
            TypeIdentifierPair type_ids_requested_by;
            ReturnCode_t return_code_requested_by {eprosima::fastdds::dds::RETCODE_OK};
            return_code_requested_by =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_requested_by);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_requested_by)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_requested_by))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_requested_by = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_requested_by = 0x00000000;
            bool common_requested_by_ec {false};
            CommonStructMember common_requested_by {TypeObjectUtils::build_common_struct_member(member_id_requested_by, member_flags_requested_by, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_requested_by, common_requested_by_ec))};
            if (!common_requested_by_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure requested_by member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_requested_by = "requested_by";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_requested_by;
            ann_custom_ServerQuery.reset();
            CompleteMemberDetail detail_requested_by = TypeObjectUtils::build_complete_member_detail(name_requested_by, member_ann_builtin_requested_by, ann_custom_ServerQuery);
            CompleteStructMember member_requested_by = TypeObjectUtils::build_complete_struct_member(common_requested_by, detail_requested_by);
            TypeObjectUtils::add_complete_struct_member(member_seq_ServerQuery, member_requested_by);
        }
        {
            TypeIdentifierPair type_ids_requested_data_type;
            ReturnCode_t return_code_requested_data_type {eprosima::fastdds::dds::RETCODE_OK};
            return_code_requested_data_type =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "safe_edge::pilot_server::RequestedDataType", type_ids_requested_data_type);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_requested_data_type)
            {
                ::safe_edge::pilot_server::register_RequestedDataType_type_identifier(type_ids_requested_data_type);
            }
            StructMemberFlag member_flags_requested_data_type = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_requested_data_type = 0x00000001;
            bool common_requested_data_type_ec {false};
            CommonStructMember common_requested_data_type {TypeObjectUtils::build_common_struct_member(member_id_requested_data_type, member_flags_requested_data_type, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_requested_data_type, common_requested_data_type_ec))};
            if (!common_requested_data_type_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure requested_data_type member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_requested_data_type = "requested_data_type";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_requested_data_type;
            ann_custom_ServerQuery.reset();
            CompleteMemberDetail detail_requested_data_type = TypeObjectUtils::build_complete_member_detail(name_requested_data_type, member_ann_builtin_requested_data_type, ann_custom_ServerQuery);
            CompleteStructMember member_requested_data_type = TypeObjectUtils::build_complete_struct_member(common_requested_data_type, detail_requested_data_type);
            TypeObjectUtils::add_complete_struct_member(member_seq_ServerQuery, member_requested_data_type);
        }
        CompleteStructType struct_type_ServerQuery = TypeObjectUtils::build_complete_struct_type(struct_flags_ServerQuery, header_ServerQuery, member_seq_ServerQuery);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ServerQuery, type_name_ServerQuery.to_string(), type_ids_ServerQuery))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "safe_edge::pilot_server::ServerQuery already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace pilot_server

} // namespace safe_edge

