// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file pilot_serverCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__SAFE_EDGE_PILOT_SERVER_PILOT_SERVERCDRAUX_HPP
#define FAST_DDS_GENERATED__SAFE_EDGE_PILOT_SERVER_PILOT_SERVERCDRAUX_HPP

#include "pilot_server.hpp"

constexpr uint32_t safe_edge_pilot_server_TransitMetrics_max_cdr_typesize {137232UL};
constexpr uint32_t safe_edge_pilot_server_TransitMetrics_max_key_cdr_typesize {0UL};

constexpr uint32_t safe_edge_pilot_server_ChargingSession_max_cdr_typesize {804UL};
constexpr uint32_t safe_edge_pilot_server_ChargingSession_max_key_cdr_typesize {0UL};

constexpr uint32_t safe_edge_pilot_server_ChargerLocation_max_cdr_typesize {288UL};
constexpr uint32_t safe_edge_pilot_server_ChargerLocation_max_key_cdr_typesize {0UL};

constexpr uint32_t safe_edge_pilot_server_RouteMetric_max_cdr_typesize {268UL};
constexpr uint32_t safe_edge_pilot_server_RouteMetric_max_key_cdr_typesize {0UL};

constexpr uint32_t safe_edge_pilot_server_ServerQuery_max_cdr_typesize {268UL};
constexpr uint32_t safe_edge_pilot_server_ServerQuery_max_key_cdr_typesize {0UL};





constexpr uint32_t safe_edge_pilot_server_TransitHealth_max_cdr_typesize {272UL};
constexpr uint32_t safe_edge_pilot_server_TransitHealth_max_key_cdr_typesize {0UL};




constexpr uint32_t safe_edge_pilot_server_ChargerType_max_cdr_typesize {268UL};
constexpr uint32_t safe_edge_pilot_server_ChargerType_max_key_cdr_typesize {0UL};





namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const safe_edge::pilot_server::ChargerLocation& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const safe_edge::pilot_server::ChargerType& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const safe_edge::pilot_server::ChargingSession& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const safe_edge::pilot_server::TransitHealth& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const safe_edge::pilot_server::RouteMetric& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const safe_edge::pilot_server::TransitMetrics& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const safe_edge::pilot_server::ServerQuery& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__SAFE_EDGE_PILOT_SERVER_PILOT_SERVERCDRAUX_HPP

